desktop_products = [

    # =========================
    # ASUS DESKTOP – BUSINESS
    # =========================
    {
        "id": "desktop-asus-expertcenter-d7",
        "name": "ASUS ExpertCenter D7",
        "brand": "asus",

        "category_key": "desktop",
        "category": "Business Desktop PC",

        "sub_category": "asus",
        "series": "expertcenter",

        "application": ["desktop", "office", "enterprise"],

        "price": 54990,
        "image": "/static/images/asus expertcenter d7.webp",

        "cores": 8,
        "threads": 16,
        "socket": "LGA1200",
        "tech": "14nm",

        "form_factor": "tower",

        "description": "A reliable business desktop designed for productivity and enterprise workloads, featuring Intel Core processors, fast SSD storage, enterprise security, and compact tower design."
    },

    # =========================
    # ASUS DESKTOP – MINI PC
    # =========================
    {
        "id": "desktop-asus-expertcenter-mini-pn64",
        "name": "ASUS ExpertCenter Mini PN64",
        "brand": "asus",

        "category_key": "desktop",
        "category": "Mini Business Desktop",

        "sub_category": "asus",
        "series": "mini-pc",

        "application": ["desktop", "office", "enterprise"],

        "price": 42990,
        "image": "/static/images/asus_expertcenter_mini.jpg",

        "cores": 6,
        "threads": 12,
        "socket": "BGA",
        "tech": "10nm",

        "form_factor": "mini",

        "description": "An ultra-compact business mini PC offering powerful performance in a space-saving design, ideal for offices, kiosks, and enterprise deployments."
    },
    {
    "id": "desktop-asus-expertcenter-d5",
    "name": "ASUS ExpertCenter D5",
    "brand": "asus",
    "series": "expertcenter",
    "category_key": "desktop",
    "sub_category": "asus",
    "category": "Business Desktop PC",
    "application": "Office / Enterprise / Productivity",
    "description": "Reliable business desktop designed for daily office workloads with enterprise-grade security.",
    "processor": "Intel Core i5-12400",
    "memory": "16 GB DDR4",
    "storage": "512 GB NVMe SSD",
    "graphics": "Intel UHD Graphics 730",
    "network": "Gigabit LAN + Wi-Fi + Bluetooth",
    "operating_system": "Windows 11 Pro",
    "form_factor": "Tower Desktop",
    "warranty": "3 Year On-site Warranty",
    "image": "/static/images/asus expertcenter d5.webp",
    "price": 58990
  },

  {
    "id": "desktop-asus-rog-strix-ga35",
    "name": "ASUS ROG Strix GA35",
    "brand": "asus",
    "series": "gaming",
    "category_key": "desktop",
    "sub_category": "asus",
    "category": "Gaming Desktop PC",
    "application": "Gaming / Streaming / High Performance",
    "description": "High-end gaming desktop with powerful CPU and RTX graphics.",
    "processor": "AMD Ryzen 9 5900X",
    "memory": "32 GB DDR4",
    "storage": "1 TB NVMe SSD",
    "graphics": "NVIDIA GeForce RTX 3080",
    "network": "Wi-Fi 6 + Bluetooth + LAN",
    "operating_system": "Windows 11 Home",
    "form_factor": "Gaming Tower",
    "warranty": "1 Year Warranty",
    "image": "/static/images/asus rog strix ga35.jpg",
    "price": 219990
  },

  {
    "id": "desktop-asus-rog-strix-g15",
    "name": "ASUS ROG Strix G15 Desktop",
    "brand": "asus",
    "series": "gaming",
    "category_key": "desktop",
    "sub_category": "asus",
    "category": "Gaming Desktop PC",
    "application": "Gaming / Creative Work",
    "description": "Compact gaming desktop optimized for esports and AAA titles.",
    "processor": "AMD Ryzen 7 5800X",
    "memory": "16 GB DDR4",
    "storage": "1 TB SSD",
    "graphics": "NVIDIA GeForce RTX 3060",
    "network": "Wi-Fi 6 + Bluetooth",
    "operating_system": "Windows 11 Home",
    "form_factor": "Compact Tower",
    "warranty": "1 Year Warranty",
    "image": "/static/images/rog strix g15.jpg",
    "price": 139990
  },

  {
    "id": "desktop-lenovo-thinkcentre-m70s",
    "name": "Lenovo ThinkCentre M70s",
    "brand": "lenovo",
    "series": "thinkcentre",
    "category_key": "desktop",
    "sub_category": "lenovo",
    "category": "Business Desktop PC",
    "application": "Office / Enterprise",
    "description": "Small form factor enterprise desktop with robust security features.",
    "processor": "Intel Core i7-10700",
    "memory": "16 GB DDR4",
    "storage": "512 GB SSD",
    "graphics": "Intel UHD Graphics 630",
    "network": "Wi-Fi + Bluetooth + LAN",
    "operating_system": "Windows 10 Pro",
    "form_factor": "Small Form Factor",
    "warranty": "3 Year On-site Warranty",
    "image": "/static/images/lenovo thinkcenter m70s.jpg",
    "price": 74990
  },

  {
    "id": "desktop-lenovo-legion-tower-5",
    "name": "Lenovo Legion Tower 5",
    "brand": "lenovo",
    "series": "gaming",
    "category_key": "desktop",
    "sub_category": "lenovo",
    "category": "Gaming Desktop PC",
    "application": "Gaming / Content Creation",
    "description": "Powerful gaming tower built for immersive performance.",
    "processor": "AMD Ryzen 7 5800",
    "memory": "16 GB DDR4",
    "storage": "1 TB NVMe SSD",
    "graphics": "NVIDIA GeForce RTX 3060",
    "network": "Wi-Fi + Bluetooth",
    "operating_system": "Windows 11 Home",
    "form_factor": "Gaming Tower",
    "warranty": "1 Year Warranty",
    "image": "/static/images/lenovo legion tower 5.jpg",
    "price": 119990
  },

  {
    "id": "desktop-lenovo-thinkstation-p350",
    "name": "Lenovo ThinkStation P350",
    "brand": "lenovo",
    "series": "thinkstation",
    "category_key": "desktop",
    "sub_category": "lenovo",
    "category": "Workstation Desktop",
    "application": "Engineering / CAD / AI Workloads",
    "description": "Entry workstation certified for professional applications.",
    "processor": "Intel Core i9-11900",
    "memory": "32 GB DDR4 ECC",
    "storage": "1 TB NVMe SSD",
    "graphics": "NVIDIA RTX A2000",
    "network": "LAN",
    "operating_system": "Windows 11 Pro",
    "form_factor": "Tower Workstation",
    "warranty": "3 Year On-site Warranty",
    "image": "/static/images/lenovo thinkstation p350.jpg",
    "price": 189990
  },

  {
    "id": "desktop-dell-optiplex-7090",
    "name": "Dell OptiPlex 7090",
    "brand": "dell",
    "series": "optiplex",
    "category_key": "desktop",
    "sub_category": "dell",
    "category": "Business Desktop PC",
    "application": "Office / Enterprise",
    "description": "Enterprise desktop with advanced manageability.",
    "processor": "Intel Core i7-11700",
    "memory": "16 GB DDR4",
    "storage": "512 GB SSD",
    "graphics": "Intel UHD Graphics 750",
    "network": "LAN",
    "operating_system": "Windows 11 Pro",
    "form_factor": "Small Form Factor",
    "warranty": "3 Year ProSupport",
    "image": "/static/images/dell optiplex 7090.jpg",
    "price": 82990
  },

  {
    "id": "desktop-dell-precision-3660",
    "name": "Dell Precision 3660",
    "brand": "dell",
    "series": "precision",
    "category_key": "desktop",
    "sub_category": "dell",
    "category": "Workstation Desktop",
    "application": "3D / AI / Engineering",
    "description": "High-performance workstation for demanding professional workloads.",
    "processor": "Intel Core i9-12900",
    "memory": "32 GB DDR5",
    "storage": "1 TB NVMe SSD",
    "graphics": "NVIDIA RTX A4000",
    "network": "LAN",
    "operating_system": "Windows 11 Pro",
    "form_factor": "Tower Workstation",
    "warranty": "3 Year ProSupport",
    "image": "/static/images/dell precision 3660.jpg",
    "price": 249990
  },

  {
    "id": "desktop-hp-prodesk-400-g7",
    "name": "HP ProDesk 400 G7",
    "brand": "hp",
    "series": "prodesk",
    "category_key": "desktop",
    "sub_category": "hp",
    "category": "Business Desktop PC",
    "application": "Office / Enterprise",
    "description": "Affordable and secure business desktop.",
    "processor": "Intel Core i5-10500",
    "memory": "16 GB DDR4",
    "storage": "512 GB SSD",
    "graphics": "Intel UHD Graphics 630",
    "network": "LAN",
    "operating_system": "Windows 10 Pro",
    "form_factor": "Microtower",
    "warranty": "3 Year On-site Warranty",
    "image": "/static/images/HP proDesk 400 G7 Desktop.png",
    "price": 56990
  },

  {
    "id": "desktop-hp-z4-g4",
    "name": "HP Z4 G4 Workstation",
    "brand": "hp",
    "series": "z-workstation",
    "category_key": "desktop",
    "sub_category": "hp",
    "category": "Workstation Desktop",
    "application": "AI / Rendering / Engineering",
    "description": "Powerful workstation supporting Xeon processors.",
    "processor": "Intel Xeon W-2245",
    "memory": "64 GB DDR4 ECC",
    "storage": "2 TB NVMe SSD",
    "graphics": "NVIDIA RTX A5000",
    "network": "LAN",
    "operating_system": "Windows 11 Pro",
    "form_factor": "Tower Workstation",
    "warranty": "3 Year On-site Warranty",
    "image": "/static/images/hp z4g4.jpg",
    "price": 329990
  },
  {
    "id": "desktop-dell-vostro-5000",
    "name": "Dell Vostro 5000",
    "brand": "dell",
    "series": "vostro",
    "category_key": "desktop",
    "sub_category": "dell",
    "category": "Business Desktop PC",
    "application": "Small Business / Office",
    "description": "Affordable and reliable desktop for small business workloads.",
    "processor": "Intel Core i5-11400",
    "memory": "16 GB DDR4",
    "storage": "512 GB SSD",
    "graphics": "Intel UHD Graphics 730",
    "network": "Gigabit LAN + Wi-Fi + Bluetooth",
    "operating_system": "Windows 11 Pro",
    "form_factor": "Tower Desktop",
    "warranty": "1 Year Warranty",
    "image": "/static/images/dell vostro 5000.jpg",
    "price": 60990
  },

  {
    "id": "desktop-dell-pro-tower-plus-qbt1250",
    "name": "Dell Pro Tower Plus QBT1250",
    "brand": "dell",
    "series": "pro",
    "category_key": "desktop",
    "sub_category": "dell",
    "category": "Business Desktop PC",
    "application": "Enterprise / Productivity",
    "description": "Modern Dell Pro series desktop for enterprise environments.",
    "processor": "Intel Core i7-14700",
    "memory": "32 GB DDR5",
    "storage": "1 TB NVMe SSD",
    "graphics": "Intel UHD Graphics",
    "network": "LAN + Wi-Fi 6E + Bluetooth",
    "operating_system": "Windows 11 Pro",
    "form_factor": "Tower Desktop",
    "warranty": "3 Year ProSupport",
    "image": "/static/images/dell_pro_tower_plus_qbt1250.jpg",
    "price": 124990
  },

  {
    "id": "desktop-dell-pro-slim-qcs1250",
    "name": "Dell Pro Slim QCS1250",
    "brand": "dell",
    "series": "pro",
    "category_key": "desktop",
    "sub_category": "dell",
    "category": "Business Desktop PC",
    "application": "Office / Enterprise",
    "description": "Slim form factor desktop optimized for modern offices.",
    "processor": "Intel Core i5-14500",
    "memory": "16 GB DDR5",
    "storage": "512 GB NVMe SSD",
    "graphics": "Intel UHD Graphics",
    "network": "LAN + Wi-Fi",
    "operating_system": "Windows 11 Pro",
    "form_factor": "Slim Desktop",
    "warranty": "3 Year ProSupport",
    "image": "/static/images/dell_pro_slim_qcs1250.jpg",
    "price": 88990
  },

  {
    "id": "desktop-dell-tower-ect1250",
    "name": "Dell Tower ECT1250",
    "brand": "dell",
    "series": "tower",
    "category_key": "desktop",
    "sub_category": "dell",
    "category": "Desktop PC",
    "application": "Office / General Use",
    "description": "Entry-level tower desktop for everyday workloads.",
    "processor": "Intel Core i3-13100",
    "memory": "8 GB DDR4",
    "storage": "512 GB SSD",
    "graphics": "Intel UHD Graphics",
    "network": "LAN",
    "operating_system": "Windows 11 Home",
    "form_factor": "Tower Desktop",
    "warranty": "1 Year Warranty",
    "image": "/static/images/dell_tower_ect1250.jpg",
    "price": 44990
  },

  {
    "id": "desktop-dell-pro-tower-qct1250",
    "name": "Dell Pro Tower QCT1250",
    "brand": "dell",
    "series": "pro",
    "category_key": "desktop",
    "sub_category": "dell",
    "category": "Business Desktop PC",
    "application": "Enterprise / Productivity",
    "description": "Balanced performance desktop for enterprise users.",
    "processor": "Intel Core i7-13700",
    "memory": "16 GB DDR5",
    "storage": "1 TB NVMe SSD",
    "graphics": "Intel UHD Graphics",
    "network": "LAN + Wi-Fi",
    "operating_system": "Windows 11 Pro",
    "form_factor": "Tower Desktop",
    "warranty": "3 Year ProSupport",
    "image": "/static/images/dell_pro_tower_qct1250.jpg",
    "price": 109990
  },

  {
    "id": "desktop-dell-pro-slim-plus-qbs1250",
    "name": "Dell Pro Slim Plus QBS1250",
    "brand": "dell",
    "series": "pro",
    "category_key": "desktop",
    "sub_category": "dell",
    "category": "Business Desktop PC",
    "application": "Office / Enterprise",
    "description": "Compact yet powerful slim desktop.",
    "processor": "Intel Core i7-14700",
    "memory": "32 GB DDR5",
    "storage": "1 TB NVMe SSD",
    "graphics": "Intel UHD Graphics",
    "network": "Wi-Fi 6E + LAN",
    "operating_system": "Windows 11 Pro",
    "form_factor": "Slim Desktop",
    "warranty": "3 Year ProSupport",
    "image": "/static/images/dell_pro_slim_plus_qbs1250.jpg",
    "price": 134990
  },

  {
    "id": "desktop-dell-slim-ecs1250",
    "name": "Dell Slim ECS1250",
    "brand": "dell",
    "series": "slim",
    "category_key": "desktop",
    "sub_category": "dell",
    "category": "Desktop PC",
    "application": "Office / Home",
    "description": "Space-saving slim desktop for home and office use.",
    "processor": "Intel Core i5-13400",
    "memory": "16 GB DDR4",
    "storage": "512 GB SSD",
    "graphics": "Intel UHD Graphics",
    "network": "LAN",
    "operating_system": "Windows 11 Home",
    "form_factor": "Slim Desktop",
    "warranty": "1 Year Warranty",
    "image": "/static/images/dell_slim_ecs1250.jpg",
    "price": 54990
  },

  {
    "id": "desktop-dell-pro-24-aio-qc24250",
    "name": "Dell Pro 24 AIO QC24250",
    "brand": "dell",
    "series": "pro",
    "category_key": "desktop",
    "sub_category": "dell",
    "category": "All-in-One Desktop",
    "application": "Office / Enterprise",
    "description": "All-in-one desktop with clean cable-free workspace.",
    "processor": "Intel Core i5-14500",
    "memory": "16 GB DDR5",
    "storage": "512 GB SSD",
    "graphics": "Intel UHD Graphics",
    "network": "Wi-Fi + Bluetooth",
    "operating_system": "Windows 11 Pro",
    "form_factor": "All-in-One",
    "warranty": "3 Year ProSupport",
    "image": "/static/images/dell_pro_24_aio.jpg",
    "price": 97990
  },

  {
    "id": "desktop-dell-pro-micro-qcm1250",
    "name": "Dell Pro Micro QCM1250",
    "brand": "dell",
    "series": "pro",
    "category_key": "desktop",
    "sub_category": "dell",
    "category": "Mini PC",
    "application": "Enterprise / Space Saving",
    "description": "Ultra-compact micro desktop for space-constrained environments.",
    "processor": "Intel Core i5-14500T",
    "memory": "16 GB DDR5",
    "storage": "512 GB NVMe SSD",
    "graphics": "Intel UHD Graphics",
    "network": "Wi-Fi + LAN",
    "operating_system": "Windows 11 Pro",
    "form_factor": "Micro PC",
    "warranty": "3 Year ProSupport",
    "image": "/static/images/dell_pro_micro_qcm1250.jpg",
    "price": 81990
  },

  {
    "id": "desktop-dell-pro-micro-plus-qbm1250",
    "name": "Dell Pro Micro Plus QBM1250",
    "brand": "dell",
    "series": "pro",
    "category_key": "desktop",
    "sub_category": "dell",
    "category": "Mini PC",
    "application": "Enterprise / Advanced Productivity",
    "description": "High-end micro desktop with enhanced performance.",
    "processor": "Intel Core i7-14700T",
    "memory": "32 GB DDR5",
    "storage": "1 TB NVMe SSD",
    "graphics": "Intel UHD Graphics",
    "network": "Wi-Fi 6E + LAN",
    "operating_system": "Windows 11 Pro",
    "form_factor": "Micro PC",
    "warranty": "3 Year ProSupport",
    "image": "/static/images/dell_pro_micro_plus_qbm1250.jpg",
    "price": 109990
  },

  {
    "id": "desktop-hp-z2-mini-g5",
    "name": "HP Z2 Mini G5",
    "brand": "hp",
    "series": "z-workstation",
    "category_key": "desktop",
    "sub_category": "hp",
    "category": "Mini Workstation",
    "application": "CAD / AI / Professional Workloads",
    "description": "Compact workstation delivering serious performance.",
    "processor": "Intel Core i7-10700",
    "memory": "32 GB DDR4",
    "storage": "1 TB NVMe SSD",
    "graphics": "NVIDIA Quadro P1000",
    "network": "LAN",
    "operating_system": "Windows 11 Pro",
    "form_factor": "Mini Workstation",
    "warranty": "3 Year On-site Warranty",
    "image": "/static/images/HP-z2-mini-g5-side.jpg",
    "price": 179990
  },

  {
    "id": "desktop-hp-elite-800-g9",
    "name": "HP Elite 800 G9 Desktop",
    "brand": "hp",
    "series": "elitedesk",
    "category_key": "desktop",
    "sub_category": "hp",
    "category": "Enterprise Desktop PC",
    "application": "Enterprise / Corporate",
    "description": "Premium enterprise desktop with enhanced security and performance.",
    "processor": "Intel Core i7-13700",
    "memory": "16 GB DDR5",
    "storage": "1 TB NVMe SSD",
    "graphics": "Intel UHD Graphics",
    "network": "Wi-Fi 6E + LAN",
    "operating_system": "Windows 11 Pro",
    "form_factor": "Small Form Factor",
    "warranty": "3 Year On-site Warranty",
    "image": "/static/images/hp_elite_800_g9.jpg",
    "price": 119990
  }


]
