cpu_products = [
  
{
"id":"epyc-9965",
"name":"AMD EPYC 9965",
"brand":"AMD",
"category":"AMD Server Processor",
"application":"Server",
"description":"AMD EPYC™ (One-Hundred-Ninety-Two-Core) Model 9965",
"series":"turin-9005-series",
"socket":"SP5",
"cores":192,
"threads":384,
"category_key": "cpu",
"sub_category": "amd-server",
"base_freq":2.25,
"max_boost_freq":3.70,
"cache":384,
"tdp":500,
"tech":"Zen 5c",
"memory_type":"DDR5",
"max_memory_size":6144,
"memory_speed":6400,
"pcie_gen5_lanes":160,
"socket_support":"2P/1P",
"packaging":"Tray",
"image": "/static/images/AMD EPYC 9005 and 9004 series.jpg",
"price":110.00
},

{
"id":"epyc-9845",
"name":"AMD EPYC 9845",
"brand":"AMD",
"category":"AMD Server Processor",
"application":"Server",
"description":"AMD EPYC™ (One-Hundred-Sixty-Core) Model 9845",
"series":"turin-9005-series",
"socket":"SP5",
"cores":160,
"threads":320,
"category_key": "cpu",
"sub_category": "amd-server",
"base_freq":2.10,
"max_boost_freq":3.70,
"cache":320,
"tdp":390,
"tech":"Zen 5c",
"memory_type":"DDR5",
"max_memory_size":6144,
"memory_speed":6400,
"pcie_gen5_lanes":160,
"socket_support":"2P/1P",
"packaging":"Tray",
"image": "/static/images/AMD EPYC 9005 and 9004 series.jpg",
"price":150
},
{
"id":"epyc-9825",
"name":"AMD EPYC 9825",
"brand":"AMD",
"category":"AMD Server Processor",
"application":"Server",
"description":"AMD EPYC™ (One-Hundred-Sixty-Core) Model 9845",
"series":"turin-9005-series",
"socket":"SP5",
"cores":144,
"threads":288,
"category_key": "cpu",
"sub_category": "amd-server",
"base_freq":2.20,
"max_boost_freq":3.70,
"cache":384,
"tdp":390,
"tech":"Zen 5c",
"memory_type":"DDR5",
"max_memory_size":6144,
"memory_speed":6400,
"pcie_gen5_lanes":160,
"socket_support":"2P/1P",
"packaging":"Tray",
"image": "/static/images/AMD EPYC 9005 and 9004 series.jpg",
"price":125
},
{
"id":"epyc-9755",
"name":"AMD EPYC 9755",
"brand":"AMD",
"category":"AMD Server Processor",
"application":"Server",
"description":"AMD EPYC™ (One-Twenty-Eight-Core) Model 9755",
"series":"turin-9005-series",
"socket":"SP5",
"cores":128,
"threads":256,
"category_key": "cpu",
"sub_category": "amd-server",
"base_freq":2.70,
"max_boost_freq":4.10,
"cache":512,
"tdp":500,
"tech":"Zen 5",
"memory_type":"DDR5",
"max_memory_size":6144,
"memory_speed":6400,
"pcie_gen5_lanes":160,
"socket_support":"2P/1P",
"packaging":"Tray",
"image": "/static/images/AMD EPYC 9005 and 9004 series.jpg",
"price":115
},
{
"id":"epyc-9745",
"name":"AMD EPYC 9745",
"brand":"AMD",
"category":"AMD Server Processor",
"application":"Server",
"description":"AMD EPYC™ (One-Twenty-Eight-Core) Model 9745",
"series":"turin-9005-series",
"socket":"SP5",
"cores":128,
"threads":256,
"category_key": "cpu",
"sub_category": "amd-server",
"base_freq":2.40,
"max_boost_freq":3.70,
"cache":256,
"tdp":400,
"tech":"Zen 5c",
"memory_type":"DDR5",
"max_memory_size":6144,
"memory_speed":6400,
"pcie_gen5_lanes":160,
"socket_support":"2P/1P",
"packaging":"Tray",
"image": "/static/images/AMD EPYC 9005 and 9004 series.jpg",
"price":115
},
{
"id":"epyc-9655",
"name":"AMD EPYC 9655",
"brand":"AMD",
"category":"AMD Server Processor",
"application":"Server",
"description":"AMD EPYC™ (Ninety-Six-Core) Model 9655",
"series":"turin-9005-series",
"socket":"SP5",
"cores":96,
"threads":192,
"category_key": "cpu",
"sub_category": "amd-server",
"base_freq":2.60,
"max_boost_freq":4.50,
"cache":384,
"tdp":400,
"tech":"Zen 5",
"memory_type":"DDR5",
"max_memory_size":6144,
"memory_speed":6400,
"pcie_gen5_lanes":160,
"socket_support":"2P/1P",
"packaging":"Tray",
"image": "/static/images/AMD EPYC 9005 and 9004 series.jpg",
"price":110
},
{
"id":"epyc-9655p",
"name":"AMD EPYC 9655P",
"brand":"AMD",
"category":"AMD Server Processor",
"application":"Server",
"description":"AMD EPYC™ (Ninety-Six-Core) Model 9655P",
"series":"turin-9005-series",
"socket":"SP5",
"cores":96,
"threads":192,
"category_key": "cpu",
"sub_category": "amd-server",
"base_freq":2.60,
"max_boost_freq":4.50,
"cache":384,
"tdp":400,
"tech":"Zen 5",
"memory_type":"DDR5",
"max_memory_size":6144,
"memory_speed":6400,
"pcie_gen5_lanes":160,
"socket_support":"1P",
"packaging":"Tray",
"image": "/static/images/AMD EPYC 9005 and 9004 series.jpg",
"price":112
},
{
"id":"epyc-9645",
"name":"AMD EPYC 9645",
"brand":"AMD",
"category":"AMD Server Processor",
"application":"Server",
"description":"AMD EPYC™ (Ninety-Six-Core) Model 9645",
"series":"turin-9005-series",
"socket":"SP5",
"cores":96,
"threads":192,
"category_key": "cpu",
"sub_category": "amd-server",
"base_freq":2.30,
"max_boost_freq":3.70,
"cache":256,
"tdp":320,
"tech":"Zen 5c",
"memory_type":"DDR5",
"max_memory_size":6144,
"memory_speed":6400,
"pcie_gen5_lanes":160,
"socket_support":"2P/1P",
"packaging":"Tray",
"image": "/static/images/AMD EPYC 9005 and 9004 series.jpg",
"price":113
},
{
"id":"epyc-9565",
"name":"AMD EPYC 9565",
"brand":"AMD",
"category":"AMD Server Processor",
"application":"Server",
"description":"AMD EPYC™ (Seventy-Two-Core) Model 9565",
"series":"turin-9005-series",
"socket":"SP5",
"cores":72,
"threads":144,
"category_key": "cpu",
"sub_category": "amd-server",
"base_freq":3.15,
"max_boost_freq":4.30,
"cache":384,
"tdp":400,
"tech":"Zen 5",
"memory_type":"DDR5",
"max_memory_size":6144,
"memory_speed":6400,
"pcie_gen5_lanes":160,
"socket_support":"2P/1P",
"packaging":"Tray",
"image": "/static/images/AMD EPYC 9005 and 9004 series.jpg",
"price":110
},
{
"id":"epyc-9575f",
"name":"AMD EPYC 9575F",
"brand":"AMD",
"category":"AMD Server Processor",
"application":"Server",
"description":"AMD EPYC™ (Sixty-Four-Core) Model 9575F",
"series":"turin-9005-series",
"socket":"SP5",
"cores":64,
"threads":128,
"category_key": "cpu",
"sub_category": "amd-server",
"base_freq":3.30,
"max_boost_freq":5.00,
"cache":256,
"tdp":400,
"tech":"Zen 5",
"memory_type":"DDR5",
"max_memory_size":6144,
"memory_speed":6400,
"pcie_gen5_lanes":160,
"socket_support":"2P/1P",
"packaging":"Tray",
"image": "/static/images/AMD EPYC 9005 and 9004 series.jpg",
"price":100
},
{
"id":"cpu-epyc-9555",
"name":"AMD EPYC 9555",
"brand":"AMD",
"category":"AMD Server Processor",
"application":"Server",
"description":"AMD EPYC™ (Sixty-Four-Core) Model 9555",
"series":"turin-9005-series",
"socket":"SP5",
"cores":64,
"threads":128,
"category_key": "cpu",
"sub_category": "amd-server",
"base_freq":3.20,
"max_boost_freq":4.40,
"cache":256,
"tdp":360,
"tech":"Zen 5",
"memory_type":"DDR5",
"max_memory_size":6144,
"memory_speed":6400,
"pcie_gen5_lanes":160,
"socket_support":"2P/1P",
"packaging":"Tray",
"image": "/static/images/AMD EPYC 9005 and 9004 series.jpg",
"price":115
},
{
"id":"epyc-9555p",
"name":"AMD EPYC 9555P",
"brand":"AMD",
"category":"AMD Server Processor",
"application":"Server",
"description":"AMD EPYC™ (Sixty-Four-Core) Model 9555P",
"series":"turin-9005-series",
"socket":"SP5",
"cores":64,
"threads":128,
"category_key": "cpu",
"sub_category": "amd-server",
"base_freq":3.20,
"max_boost_freq":4.40,
"cache":256,
"tdp":360,
"tech":"Zen 5",
"memory_type":"DDR5",
"max_memory_size":6144,
"memory_speed":6400,
"pcie_gen5_lanes":160,
"socket_support":"1P",
"packaging":"Tray",
"image": "/static/images/AMD EPYC 9005 and 9004 series.jpg",
"price":120
},
{
"id":"epyc-9535",
"name":"AMD EPYC 9535",
"brand":"AMD",
"category":"AMD Server Processor",
"application":"Server",
"description":"AMD EPYC™ (Sixty-Four-Core) Model 9535",
"series":"turin-9005-series",
"socket":"SP5",
"cores":64,
"threads":128,
"category_key": "cpu",
"sub_category": "amd-server",
"base_freq":2.40,
"max_boost_freq":4.30,
"cache":256,
"tdp":300,
"tech":"Zen 5",
"memory_type":"DDR5",
"max_memory_size":6144,
"memory_speed":6400,
"pcie_gen5_lanes":160,
"socket_support":"2P/1P",
"packaging":"Tray",
"image": "/static/images/AMD EPYC 9005 and 9004 series.jpg",
"price":110
},
{
"id":"epyc-9475f",
"name":"AMD EPYC 9475F",
"brand":"AMD",
"category":"AMD Server Processor",
"application":"Server",
"description":"AMD EPYC™ (Forty-Eight-Core) Model 9475F",
"series":"turin-9005-series",
"socket":"SP5",
"cores":48,
"threads":96,
"category_key": "cpu",
"sub_category": "amd-server",
"base_freq":3.65,
"max_boost_freq":4.80,
"cache":256,
"tdp":400,
"tech":"Zen 5",
"memory_type":"DDR5",
"max_memory_size":6144,
"memory_speed":6400,
"pcie_gen5_lanes":160,
"socket_support":"2P/1P",
"packaging":"Tray",
"image": "/static/images/AMD EPYC 9005 and 9004 series.jpg",
"price":125
},
{
"id":"epyc-9455",
"name":"AMD EPYC 9455",
"brand":"AMD",
"category":"AMD Server Processor",
"application":"Server",
"description":"AMD EPYC™ (Forty-Eight-Core) Model 9455",
"series":"turin-9005-series",
"socket":"SP5",
"cores":48,
"threads":96,
"category_key": "cpu",
"sub_category": "amd-server",
"base_freq":3.15,
"max_boost_freq":4.40,
"cache":256,
"tdp":300,
"tech":"Zen 5",
"memory_type":"DDR5",
"max_memory_size":6144,
"memory_speed":6400,
"pcie_gen5_lanes":160,
"socket_support":"2P/1P",
"packaging":"Tray",
"image": "/static/images/AMD EPYC 9005 and 9004 series.jpg",
"price":150
},
{
"id":"epyc-9455p",
"name":"AMD EPYC 9455P",
"brand":"AMD",
"category":"AMD Server Processor",
"application":"Server",
"description":"AMD EPYC™ (Forty-Eight-Core) Model 9455P",
"series":"turin-9005-series",
"socket":"SP5",
"cores":48,
"threads":96,
"category_key": "cpu",
"sub_category": "amd-server",
"base_freq":3.15,
"max_boost_freq":4.40,
"cache":256,
"tdp":300,
"tech":"Zen 5",
"memory_type":"DDR5",
"max_memory_size":6144,
"memory_speed":6400,
"pcie_gen5_lanes":160,
"socket_support":"1P",
"packaging":"Tray",
"image": "/static/images/AMD EPYC 9005 and 9004 series.jpg",
"price":120
},
{
"id":"epyc-9365",
"name":"AMD EPYC 9365",
"brand":"AMD",
"category":"AMD Server Processor",
"application":"Server",
"description":"AMD EPYC™ (Thirty-Six-Core) Model 9365",
"series":"turin-9005-series",
"socket":"SP5",
"cores":36,
"threads":72,
"category_key": "cpu",
"sub_category": "amd-server",
"base_freq":3.40,
"max_boost_freq":4.20,
"cache":128,
"tdp":300,
"tech":"Zen 5",
"memory_type":"DDR5",
"max_memory_size":6144,
"memory_speed":6400,
"pcie_gen5_lanes":160,
"socket_support":"2P/1P",
"packaging":"Tray",
"image": "/static/images/AMD EPYC 9005 and 9004 series.jpg",
"price":101
},
{
"id":"epyc-9375f",
"name":"AMD EPYC 9375F",
"brand":"AMD",
"category":"AMD Server Processor",
"application":"Server",
"description":"AMD EPYC™ (Thirty-Two-Core) Model 9375F",
"series":"turin-9005-series",
"socket":"SP5",
"cores":32,
"threads":64,
"category_key": "cpu",
"sub_category": "amd-server",
"base_freq":3.80,
"max_boost_freq":4.80,
"cache":256,
"tdp":320,
"tech":"Zen 5",
"memory_type":"DDR5",
"max_memory_size":6144,
"memory_speed":6400,
"pcie_gen5_lanes":160,
"socket_support":"2P/1P",
"packaging":"Tray",
"image": "/static/images/AMD EPYC 9005 and 9004 series.jpg",
"price":130
},
{
"id":"epyc-9355",
"name":"AMD EPYC 9355",
"brand":"AMD",
"category":"AMD Server Processor",
"application":"Server",
"description":"AMD EPYC™ (Thirty-Two-Core) Model 9355",
"series":"turin-9005-series",
"socket":"SP5",
"cores":32,
"threads":64,
"category_key": "cpu",
"sub_category": "amd-server",
"base_freq":3.55,
"max_boost_freq":4.40,
"cache":256,
"tdp":280,
"tech":"Zen 5",
"memory_type":"DDR5",
"max_memory_size":6144,
"memory_speed":6400,
"pcie_gen5_lanes":160,
"socket_support":"2P/1P",
"packaging":"Tray",
"image": "/static/images/AMD EPYC 9005 and 9004 series.jpg",
"price":132
},
{
"id":"epyc-9355p",
"name":"AMD EPYC 9355P",
"brand":"AMD",
"category":"AMD Server Processor",
"application":"Server",
"description":"AMD EPYC™ (Thirty-Two-Core) Model 9355P",
"series":"turin-9005-series",
"socket":"SP5",
"cores":32,
"threads":64,
"category_key": "cpu",
"sub_category": "amd-server",
"base_freq":3.55,
"max_boost_freq":4.40,
"cache":256,
"tdp":280,
"tech":"Zen 5",
"memory_type":"DDR5",
"max_memory_size":6144,
"memory_speed":6400,
"pcie_gen5_lanes":160,
"socket_support":"1P",
"packaging":"Tray",
"image": "/static/images/AMD EPYC 9005 and 9004 series.jpg",
"price":120
},
{
"id":"epyc-9335",
"name":"AMD EPYC 9335",
"brand":"AMD",
"category":"AMD Server Processor",
"application":"Server",
"description":"AMD EPYC™ (Thirty-Two-Core) Model 9355",
"series":"turin-9005-series",
"socket":"SP5",
"cores":32,
"threads":64,
"category_key": "cpu",
"sub_category": "amd-server",
"base_freq":3.00,
"max_boost_freq":4.40,
"cache":128,
"tdp":210,
"tech":"Zen 5",
"memory_type":"DDR5",
"max_memory_size":6144,
"memory_speed":6400,
"pcie_gen5_lanes":160,
"socket_support":"2P/1P",
"packaging":"Tray",
"image": "/static/images/AMD EPYC 9005 and 9004 series.jpg",
"price":121
},
{
"id":"epyc-9275f",
"name":"AMD EPYC 9275F",
"brand":"AMD",
"category":"AMD Server Processor",
"application":"Server",
"description":"AMD EPYC™ (Twenty-Four Core) Model 9275F",
"series":"turin-9005-series",
"socket":"SP5",
"cores":24,
"threads":48,
"category_key": "cpu",
"sub_category": "amd-server",
"base_freq":4.10,
"max_boost_freq":4.80,
"cache":256,
"tdp":320,
"tech":"Zen 5",
"memory_type":"DDR5",
"max_memory_size":6144,
"memory_speed":6400,
"pcie_gen5_lanes":160,
"socket_support":"2P/1P",
"packaging":"Tray",
"image": "/static/images/AMD EPYC 9005 and 9004 series.jpg",
"price":120
},
{
"id":"epyc-9255",
"name":"AMD EPYC 9255",
"brand":"AMD",
"category":"AMD Server Processor",
"application":"Server",
"description":"AMD EPYC™ (Twenty-Four Core) Model 9255",
"series":"turin-9005-series",
"socket":"SP5",
"cores":24,
"threads":48,
"category_key": "cpu",
"sub_category": "amd-server",
"base_freq":3.20,
"max_boost_freq":4.30,
"cache":128,
"tdp":200,
"tech":"Zen 5",
"memory_type":"DDR5",
"max_memory_size":6144,
"memory_speed":6400,
"pcie_gen5_lanes":160,
"socket_support":"2P/1P",
"packaging":"Tray",
"image": "/static/images/AMD EPYC 9005 and 9004 series.jpg",
"price":130
},
{
"id":"epyc-9175f",
"name":"AMD EPYC 9175F",
"brand":"AMD",
"category":"AMD Server Processor",
"application":"Server",
"description":"AMD EPYC™ (Sixteen-Core) Model 9175F",
"series":"turin-9005-series",
"socket":"SP5",
"cores":16,
"threads":32,
"category_key": "cpu",
"sub_category": "amd-server",
"base_freq":4.20,
"max_boost_freq":5.00,
"cache":512,
"tdp":320,
"tech":"Zen 5",
"memory_type":"DDR5",
"max_memory_size":6144,
"memory_speed":6400,
"pcie_gen5_lanes":160,
"socket_support":"2P/1P",
"packaging":"Tray",
"image": "/static/images/AMD EPYC 9005 and 9004 series.jpg",
"price":120
},
{
"id":"epyc-9135",
"name":"AMD EPYC 9135",
"brand":"AMD",
"category":"AMD Server Processor",
"application":"Server",
"description":"AMD EPYC™ (Sixteen-Core) Model 9135",
"series":"turin-9005-series",
"socket":"SP5",
"cores":16,
"threads":32,
"category_key": "cpu",
"sub_category": "amd-server",
"base_freq":3.65,
"max_boost_freq":4.30,
"cache":64,
"tdp":200,
"tech":"Zen 5",
"memory_type":"DDR5",
"max_memory_size":6144,
"memory_speed":6400,
"pcie_gen5_lanes":160,
"socket_support":"2P/1P",
"packaging":"Tray",
"image": "/static/images/AMD EPYC 9005 and 9004 series.jpg",
"price":132.00
},
{
"id":"epyc-9115",
"name":"AMD EPYC 9115",
"brand":"AMD",
"category":"AMD Server Processor",
"application":"Server",
"description":"AMD EPYC™ (Sixteen-Core) Model 9115",
"series":"turin-9005-series",
"socket":"SP5",
"cores":16,
"threads":32,
"category_key": "cpu",
"sub_category": "amd-server",
"base_freq":2.60,
"max_boost_freq":4.10,
"cache":64,
"tdp":125,
"tech":"Zen 5",
"memory_type":"DDR5",
"max_memory_size":6144,
"memory_speed":6400,
"pcie_gen5_lanes":160,
"socket_support":"2P/1P",
"packaging":"Tray",
"image": "/static/images/AMD EPYC 9005 and 9004 series.jpg",
"price":132.00
},
{
"id":"epyc-9015",
"name":"AMD EPYC 9015",
"brand":"AMD",
"category":"AMD Server Processor",
"application":"Server",
"description":"AMD EPYC™ (Eight-Core) Model 9015",
"series":"turin-9005-series",
"socket":"SP5",
"cores":8,
"threads":16,
"category_key": "cpu",
"sub_category": "amd-server",
"base_freq":3.60,
"max_boost_freq":4.10,
"cache":64,
"tdp":125,
"tech":"Zen 5",
"memory_type":"DDR5",
"max_memory_size":6144,
"memory_speed":6400,
"pcie_gen5_lanes":160,
"socket_support":"2P/1P",
"packaging":"Tray",
"image": "/static/images/AMD EPYC 9005 and 9004 series.jpg",
"price":145.00
},


#9004 series

  {
    "id": "epyc-9654p",
    "name": "AMD EPYC 9654P",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "AMD EPYC™ (Ninety-Six-Core) Model 9654P",
    "series": "genova-9004-series",
    "socket": "SP5",
    "cores": 96,
    "threads": 192,
    "category_key": "cpu",
    "sub_category": "amd-server",
    "base_freq": 2.40,
    "boost_freq": 3.70,
    "cache": 384,
    "tdp": 360,
    "tech": "5nm",
    "memory_type": "DDR5",
    "ddr5_channels": 12,
    "gen5_lanes": 128,
    "socket_support": "1P",
    "max_memory_size": 6144,
    "packaging": "Tray",
    "image": "/static/images/AMD EPYC 9005 and 9004 series.jpg",
    "price": 120
  },
  {
    "id": "epyc-9554p",
    "name": "AMD EPYC 9554P",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "AMD EPYC™ (Sixty-Four-Core) Model 9554P",
    "series": "genova-9004-series",
    "socket": "SP5",
    "cores": 64,
    "threads": 128,
    "category_key": "cpu",
    "sub_category": "amd-server",
    "base_freq": 3.10,
    "boost_freq": 3.75,
    "cache": 256,
    "tdp": 360,
    "tech": "5nm",
    "memory_type": "DDR5",
    "ddr5_channels": 12,
    "gen5_lanes": 128,
    "socket_support": "1P",
    "max_memory_size": 6144,
    "packaging": "Tray",
    "image": "/static/images/AMD EPYC 9005 and 9004 series.jpg",
    "price": 135
  },
  {
    "id": "epyc-9454p",
    "name": "AMD EPYC 9454P",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "AMD EPYC™ (Forty-Eight-Core) Model 9454P",
    "series": "genova-9004-series",
    "socket": "SP5",
    "cores": 48,
    "threads": 96,
    "category_key": "cpu",
    "sub_category": "amd-server",
    "base_freq": 2.75,
    "boost_freq": 3.80,
    "cache": 256,
    "tdp": 290,
    "tech": "5nm",
    "memory_type": "DDR5",
    "ddr5_channels": 12,
    "gen5_lanes": 128,
    "socket_support": "1P",
    "max_memory_size": 6144,
    "packaging": "Tray",
    "image": "/static/images/AMD EPYC 9005 and 9004 series.jpg",
    "price": 120
  },
  {
    "id": "epyc-9354p",
    "name": "AMD EPYC 9354P",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "AMD EPYC™ (Thirty-Two-Core) Model 9354P",
    "series": "genova-9004-series",
    "socket": "SP5",
    "cores": 32,
    "threads": 64,
    "category_key": "cpu",
    "sub_category": "amd-server",
    "base_freq": 3.25,
    "boost_freq": 3.80,
    "cache": 256,
    "tdp": 280,
    "tech": "5nm",
    "memory_type": "DDR5",
    "ddr5_channels": 12,
    "gen5_lanes": 128,
    "socket_support": "1P",
    "max_memory_size": 6144,
    "packaging": "Tray",
    "image": "/static/images/AMD EPYC 9005 and 9004 series.jpg",
    "price": 113
  },
  {
    "id": "epyc-9334",
    "name": "AMD EPYC 9334",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "AMD EPYC™ (Thirty-Two-Core) Model 9334",
    "series": "genova-9004-series",
    "socket": "SP5",
    "cores": 32,
    "threads": 64,
    "category_key": "cpu",
    "sub_category": "amd-server",
    "base_freq": 2.70,
    "boost_freq": 3.90,
    "cache": 128,
    "tdp": 210,
    "tech": "5nm",
    "memory_type": "DDR5",
    "ddr5_channels": 12,
    "gen5_lanes": 128,
    "socket_support": "2P/1P",
    "max_memory_size": 6144,
    "packaging": "Tray",
    "image": "/static/images/AMD EPYC 9005 and 9004 series.jpg",
    "price": 120
  },
  {
    "id": "epyc-9254",
    "name": "AMD EPYC 9254",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "AMD EPYC™ (Twenty-Four Core) Model 9254",
    "series": "genova-9004-series",
    "socket": "SP5",
    "cores": 24,
    "threads": 48,
    "category_key": "cpu",
    "sub_category": "amd-server",
    "base_freq": 2.90,
    "boost_freq": 4.15,
    "cache": 128,
    "tdp": 200,
    "tech": "5nm",
    "memory_type": "DDR5",
    "ddr5_channels": 12,
    "gen5_lanes": 128,
    "socket_support": "2P/1P",
    "max_memory_size": 6144,
    "packaging": "Tray",
    "image": "/static/images/AMD EPYC 9005 and 9004 series.jpg",
    "price": 110
  },
  {
    "id": "epyc-9224",
    "name": "AMD EPYC 9224",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "AMD EPYC™ (Twenty-Four Core) Model 9224",
    "series": "genova-9004-series",
    "socket": "SP5",
    "cores": 24,
    "threads": 48,
    "category_key": "cpu",
    "sub_category": "amd-server",
    "base_freq": 2.50,
    "boost_freq": 3.70,
    "cache": 64,
    "tdp": 200,
    "tech": "5nm",
    "memory_type": "DDR5",
    "ddr5_channels": 12,
    "gen5_lanes": 128,
    "socket_support": "2P/1P",
    "max_memory_size": 6144,
    "packaging": "Tray",
    "image": "/static/images/AMD EPYC 9005 and 9004 series.jpg",
    "price": 110
  },
  {
    "id": "epyc-9124",
    "name": "AMD EPYC 9124",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "AMD EPYC™ (Sixteen-Core) Model 9124",
    "series": "genova-9004-series",
    "socket": "SP5",
    "cores": 16,
    "threads": 32,
    "category_key": "cpu",
    "sub_category": "amd-server",
    "base_freq": 3.00,
    "boost_freq": 3.70,
    "cache": 64,
    "tdp": 200,
    "tech": "5nm",
    "memory_type": "DDR5",
    "ddr5_channels": 12,
    "gen5_lanes": 128,
    "socket_support": "2P/1P",
    "max_memory_size": 6144,
    "packaging": "Tray",
    "image": "/static/images/AMD EPYC 9005 and 9004 series.jpg",
    "price": 101
  },
  {
    "id": "epyc-9384x",
    "name": "AMD EPYC 9384X",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "AMD EPYC™ (Thirty-Two-Core) Model 9384X",
    "series": "genova-9004-series",
    "socket": "SP5",
    "cores": 32,
    "threads": 64,
    "category_key": "cpu",
    "sub_category": "amd-server",
    "base_freq": 3.10,
    "boost_freq": 3.90,
    "cache": 768,
    "tdp": 320,
    "tech": "5nm",
    "memory_type": "DDR5",
    "ddr5_channels": 12,
    "gen5_lanes": 128,
    "socket_support": "2P/1P",
    "max_memory_size": 6144,
    "packaging": "Tray",
    "image": "/static/images/AMD EPYC 9005 and 9004 series.jpg",
    "price": 101
  },
  {
    "id": "epyc-9184x",
    "name": "AMD EPYC 9184X",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "AMD EPYC™ (Sixteen-Core) Model 9184X",
    "series": "genova-9004-series",
    "socket": "SP5",
    "cores": 16,
    "threads": 32,
    "category_key": "cpu",
    "sub_category": "amd-server",
    "base_freq": 3.55,
    "boost_freq": 4.20,
    "cache": 768,
    "tdp": 320,
    "tech": "5nm",
    "memory_type": "DDR5",
    "ddr5_channels": 12,
    "gen5_lanes": 128,
    "socket_support": "2P/1P",
    "max_memory_size": 6144,
    "packaging": "Tray",
    "image": "/static/images/AMD EPYC 9005 and 9004 series.jpg",
    "price": 140
  },
  {
    "id": "epyc-9474f",
    "name": "AMD EPYC 9474F",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "AMD EPYC™ (Forty-Eight-Core) Model 9474F",
    "series": "genova-9004-series",
    "socket": "SP5",
    "cores": 48,
    "threads": 96,
    "category_key": "cpu",
    "sub_category": "amd-server",
    "base_freq": 3.60,
    "boost_freq": 4.10,
    "cache": 256,
    "tdp": 360,
    "tech": "5nm",
    "memory_type": "DDR5",
    "ddr5_channels": 12,
    "gen5_lanes": 128,
    "socket_support": "2P/1P",
    "max_memory_size": 6144,
    "packaging": "Tray",
    "image": "/static/images/AMD EPYC 9005 and 9004 series.jpg",
    "price": 160
  },
  {
    "id": "epyc-9374f",
    "name": "AMD EPYC 9374F",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "AMD EPYC™ (Thirty-Two-Core) Model 9374F",
    "series": "genova-9004-series",
    "socket": "SP5",
    "cores": 32,
    "threads": 64,
    "category_key": "cpu",
    "sub_category": "amd-server",
    "base_freq": 3.85,
    "boost_freq": 4.30,
    "cache": 256,
    "tdp": 320,
    "tech": "5nm",
    "memory_type": "DDR5",
    "ddr5_channels": 12,
    "gen5_lanes": 128,
    "socket_support": "2P/1P",
    "max_memory_size": 6144,
    "packaging": "Tray",
    "image": "/static/images/AMD EPYC 9005 and 9004 series.jpg",
    "price": 150
  },
  {
    "id": "epyc-9274f",
    "name": "AMD EPYC 9274F",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "AMD EPYC™ (Twenty-Four Core) Model 9274F",
    "series": "genova-9004-series",
    "socket": "SP5",
    "cores": 24,
    "threads": 48,
    "category_key": "cpu",
    "sub_category": "amd-server",
    "base_freq": 4.05,
    "boost_freq": 4.30,
    "cache": 256,
    "tdp": 320,
    "tech": "5nm",
    "memory_type": "DDR5",
    "ddr5_channels": 12,
    "gen5_lanes": 128,
    "socket_support": "2P/1P",
    "max_memory_size": 6144,
    "packaging": "Tray",
    "image": "/static/images/AMD EPYC 9005 and 9004 series.jpg",
    "price": 150
  },
  {
    "id": "epyc-9174f",
    "name": "AMD EPYC 9174F",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "AMD EPYC™ (Sixteen-Core) Model 9174F",
    "series": "genova-9004-series",
    "socket": "SP5",
    "cores": 16,
    "threads": 32,
    "category_key": "cpu",
    "sub_category": "amd-server",
    "base_freq": 4.10,
    "boost_freq": 4.40,
    "cache": 256,
    "tdp": 320,
    "tech": "5nm",
    "memory_type": "DDR5",
    "ddr5_channels": 12,
    "gen5_lanes": 128,
    "socket_support": "2P/1P",
    "max_memory_size": 6144,
    "packaging": "Tray",
    "image": "/static/images/AMD EPYC 9005 and 9004 series.jpg",
    "price": 200
  },
  
  
  #7003 series

  {
    "id": "epyc-7713p",
    "name": "AMD EPYC 7713P",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "AMD EPYC™ (Sixty-Four-Core) Model 7713P",
    "series": "milan-7003-series",
    "socket": "SP3",
    "cores": 64,
    "threads": 128,
    "category_key": "cpu",
    "sub_category": "amd-server",
    "base_freq": 2.00,
    "boost_freq": 3.675,
    "cache": 256,
    "tdp": 225,
    "tech": "7nm",
    "memory_type": "DDR4",
    "ddr_channels": 8,
    "gen4_lanes": 128,
    "socket_support": "1P",
    "max_memory_size": 4096,
    "packaging": "Tray",
    "image": "/static/images/amd_epyc_7713p.jpg",
    "price": 120
  },
  {
    "id": "epyc-7543p",
    "name": "AMD EPYC 7543P",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "AMD EPYC™ (Thirty-Two-Core) Model 7543P",
    "series": "milan-7003-series",
    "socket": "SP3",
    "cores": 32,
    "threads": 64,
    "category_key": "cpu",
    "sub_category": "amd-server",
    "base_freq": 2.80,
    "boost_freq": 3.70,
    "cache": 256,
    "tdp": 225,
    "tech": "7nm",
    "memory_type": "DDR4",
    "ddr_channels": 8,
    "gen4_lanes": 128,
    "socket_support": "1P",
    "max_memory_size": 4096,
    "packaging": "Tray",
    "image": "/static/images/amd_epyc_7543p.jpg",
    "price": 150
  },
  {
    "id": "epyc-7443p",
    "name": "AMD EPYC 7443P",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "AMD EPYC™ (Twenty-Four Core) Model 7443P",
    "series": "milan-7003-series",
    "socket": "SP3",
    "cores": 24,
    "threads": 48,
    "category_key": "cpu",
    "sub_category": "amd-server",
    "base_freq": 2.85,
    "boost_freq": 4.00,
    "cache": 128,
    "tdp": 200,
    "tech": "7nm",
    "memory_type": "DDR4",
    "ddr_channels": 8,
    "gen4_lanes": 128,
    "socket_support": "1P",
    "max_memory_size": 4096,
    "packaging": "Tray",
    "image": "/static/images/amd_epyc_7443p.jpg",
    "price": 140
  },
  {
    "id": "epyc-7413",
    "name": "AMD EPYC 7413",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "AMD EPYC™ (Twenty-Four Core) Model 7413",
    "series": "milan-7003-series",
    "socket": "SP3",
    "cores": 24,
    "threads": 48,
    "category_key": "cpu",
    "sub_category": "amd-server",
    "base_freq": 2.65,
    "boost_freq": 3.60,
    "cache": 128,
    "tdp": 180,
    "tech": "7nm",
    "memory_type": "DDR4",
    "ddr_channels": 8,
    "gen4_lanes": 128,
    "socket_support": "2P/1P",
    "max_memory_size": 4096,
    "packaging": "Tray",
    "image": "/static/images/amd_epyc_7413.jpg",
    "price": 120
  },
  {
    "id": "epyc-7343",
    "name": "AMD EPYC 7343",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "AMD EPYC™ (Sixteen-Core) Model 7343",
    "series": "milan-7003-series",
    "socket": "SP3",
    "cores": 16,
    "threads": 32,
    "category_key": "cpu",
    "sub_category": "amd-server",
    "base_freq": 3.20,
    "boost_freq": 3.90,
    "cache": 128,
    "tdp": 190,
    "tech": "7nm",
    "memory_type": "DDR4",
    "ddr_channels": 8,
    "gen4_lanes": 128,
    "socket_support": "2P/1P",
    "max_memory_size": 4096,
    "packaging": "Tray",
    "image": "/static/images/amd_epyc_7343.jpg",
    "price": 150
  },
  {
    "id": "epyc-7313",
    "name": "AMD EPYC 7313",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "AMD EPYC™ (Sixteen-Core) Model 7313",
    "series": "milan-7003-series",
    "socket": "SP3",
    "cores": 16,
    "threads": 32,
    "category_key": "cpu",
    "sub_category": "amd-server",
    "base_freq": 3.00,
    "boost_freq": 3.70,
    "cache": 128,
    "tdp": 155,
    "tech": "7nm",
    "memory_type": "DDR4",
    "ddr_channels": 8,
    "gen4_lanes": 128,
    "socket_support": "2P/1P",
    "max_memory_size": 4096,
    "packaging": "Tray",
    "image": "/static/images/amd_epyc_7313.jpg",
    "price": 170
  },
  {
    "id": "epyc-7313p",
    "name": "AMD EPYC 7313P",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "AMD EPYC™ (Sixteen-Core) Model 7313P",
    "series": "milan-7003-series",
    "socket": "SP3",
    "cores": 16,
    "threads": 32,
    "category_key": "cpu",
    "sub_category": "amd-server",
    "base_freq": 3.00,
    "boost_freq": 3.70,
    "cache": 128,
    "tdp": 155,
    "tech": "7nm",
    "memory_type": "DDR4",
    "ddr_channels": 8,
    "gen4_lanes": 128,
    "socket_support": "1P",
    "max_memory_size": 4096,
    "packaging": "Tray",
    "image": "/static/images/amd_epyc_7313p.jpg",
    "price": 120
  },
  {
    "id": "epyc-7303",
    "name": "AMD EPYC 7303",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "AMD EPYC™ (Sixteen-Core) Model 7203P",
    "series": "milan-7003-series",
    "socket": "SP3",
    "cores": 16,
    "threads": 32,
    "category_key": "cpu",
    "sub_category": "amd-server",
    "base_freq": 2.40,
    "boost_freq": 3.40,
    "cache": 64,
    "tdp": 130,
    "tech": "7nm",
    "memory_type": "DDR4",
    "ddr_channels": 8,
    "gen4_lanes": 128,
    "socket_support": "2P/1P",
    "max_memory_size": 4096,
    "packaging": "Tray",
    "image": "/static/images/amd_epyc_7303.jpg",
    "price": 140
  },
  {
    "id": "epyc-7303p",
    "name": "AMD EPYC 7303P",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "AMD EPYC™ (Sixteen-Core) Model 7303P",
    "series": "milan-7003-series",
    "socket": "SP3",
    "cores": 16,
    "threads": 32,
    "category_key": "cpu",
    "sub_category": "amd-server",
    "base_freq": 2.40,
    "boost_freq": 3.40,
    "cache": 64,
    "tdp": 130,
    "tech": "7nm",
    "memory_type": "DDR4",
    "ddr_channels": 8,
    "gen4_lanes": 128,
    "socket_support": "1P",
    "max_memory_size": 4096,
    "packaging": "Tray",
    "image": "/static/images/amd_epyc_7303p.jpg",
    "price": 180
  },
  {
    "id": "epyc-7203",
    "name": "AMD EPYC 7203",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "AMD EPYC™ (Sixteen-Core) Model 7203",
    "series": "milan-7003-series",
    "socket": "SP3",
    "cores": 8,
    "threads": 16,
    "category_key": "cpu",
    "sub_category": "amd-server",
    "base_freq": 2.80,
    "boost_freq": 3.40,
    "cache": 64,
    "tdp": 120,
    "tech": "7nm",
    "memory_type": "DDR4",
    "ddr_channels": 8,
    "gen4_lanes": 128,
    "socket_support": "2P/1P",
    "max_memory_size": 4096,
    "packaging": "Tray",
    "image": "/static/images/amd_epyc_7203.jpg",
    "price": 135
  },
  {
    "id": "epyc-7203p",
    "name": "AMD EPYC 7203P",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "AMD EPYC™ (Sixteen-Core) Model 7203P",
    "series": "milan-7003-series",
    "socket": "SP3",
    "cores": 8,
    "threads": 16,
    "category_key": "cpu",
    "sub_category": "amd-server",
    "base_freq": 2.80,
    "boost_freq": 3.40,
    "cache": 64,
    "tdp": 120,
    "tech": "7nm",
    "memory_type": "DDR4",
    "ddr_channels": 8,
    "gen4_lanes": 128,
    "socket_support": "1P",
    "max_memory_size": 4096,
    "packaging": "Tray",
    "image": "/static/images/amd_epyc_7203p.jpg",
    "price": 200
  },
  {
    "id": "epyc-7773x",
    "name": "AMD EPYC 7773X",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "AMD EPYC™ (Sixty-Four-Core) Model 7773X",
    "series": "milan-7003-series",
    "socket": "SP3",
    "cores": 64,
    "threads": 128,
    "category_key": "cpu",
    "sub_category": "amd-server",
    "base_freq": 2.20,
    "boost_freq": 3.50,
    "cache": 768,
    "tdp": 280,
    "tech": "7nm",
    "memory_type": "DDR4",
    "ddr_channels": 8,
    "gen4_lanes": 128,
    "socket_support": "2P/1P",
    "max_memory_size": 4096,
    "packaging": "Tray",
    "image": "/static/images/amd_epyc_7773x.jpg",
    "price": 165
  },
  {
    "id": "epyc-7473x",
    "name": "AMD EPYC 7473X",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "AMD EPYC™ (Twenty-Four Core) Model 7473X ",
    "series": "milan-7003-series",
    "socket": "SP3",
    "cores": 24,
    "threads": 48,
    "category_key": "cpu",
    "sub_category": "amd-server",
    "base_freq": 2.80,
    "boost_freq": 3.70,
    "cache": 768,
    "tdp": 240,
    "tech": "7nm",
    "memory_type": "DDR4",
    "ddr_channels": 8,
    "gen4_lanes": 128,
    "socket_support": "2P/1P",
    "max_memory_size": 4096,
    "packaging": "Tray",
    "image": "/static/images/amd_epyc_7473x.jpg",
    "price": 180
  },
  {
    "id": "epyc-7373x",
    "name": "AMD EPYC 7373X",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "AMD EPYC™ (Sixteen-Core) Model 7373X ",
    "series": "milan-7003-series",
    "socket": "SP3",
    "cores": 16,
    "threads": 32,
    "category_key": "cpu",
    "sub_category": "amd-server",
    "base_freq": 3.05,
    "boost_freq": 3.80,
    "cache": 768,
    "tdp": 240,
    "tech": "7nm",
    "memory_type": "DDR4",
    "ddr_channels": 8,
    "gen4_lanes": 128,
    "socket_support": "2P/1P",
    "max_memory_size": 4096,
    "packaging": "Tray",
    "image": "/static/images/amd_epyc_7373x.jpg",
    "price": 123
  },
  {
    "id": "epyc-75f3",
    "name": "AMD EPYC 75F3",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "AMD EPYC™ (Thirty-Two-Core) Model 75F3",
    "series": "milan-7003-series",
    "socket": "SP3",
    "cores": 32,
    "threads": 64,
    "category_key": "cpu",
    "sub_category": "amd-server",
    "base_freq": 2.95,
    "boost_freq": 4.00,
    "cache": 256,
    "tdp": 280,
    "tech": "7nm",
    "memory_type": "DDR4",
    "ddr_channels": 8,
    "gen4_lanes": 128,
    "socket_support": "2P/1P",
    "max_memory_size": 4096,
    "packaging": "Tray",
    "image": "/static/images/amd_epyc_75f3.jpg",
    "price": 143
  },
  {
    "id": "epyc-74f3",
    "name": "AMD EPYC 74F3",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "AMD EPYC™ (Twenty-four Core) Model 74F3",
    "series": "milan-7003-series",
    "socket": "SP3",
    "cores": 24,
    "threads": 48,
    "category_key": "cpu",
    "sub_category": "amd-server",
    "base_freq": 3.20,
    "boost_freq": 4.00,
    "cache": 256,
    "tdp": 240,
    "tech": "7nm",
    "memory_type": "DDR4",
    "ddr_channels": 8,
    "gen4_lanes": 128,
    "socket_support": "2P/1P",
    "max_memory_size": 4096,
    "packaging": "Tray",
    "image": "/static/images/amd_epyc_74f3.jpg",
    "price": 145
  },
  {
    "id": "epyc-73f3",
    "name": "AMD EPYC 73F3",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "AMD EPYC™ (Sixteen-Core) Model 73F3",
    "series": "milan-7003-series",
    "socket": "SP3",
    "cores": 16,
    "threads": 32,
    "category_key": "cpu",
    "sub_category": "amd-server",
    "base_freq": 3.50,
    "boost_freq": 4.00,
    "cache": 256,
    "tdp": 240,
    "tech": "7nm",
    "memory_type": "DDR4",
    "ddr_channels": 8,
    "gen4_lanes": 128,
    "socket_support": "2P/1P",
    "max_memory_size": 4096,
    "packaging": "Tray",
    "image": "/static/images/amd_epyc_73f3.jpg",
    "price": 135
  },
  {
    "id": "epyc-72f3",
    "name": "AMD EPYC 72F3",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "AMD EPYC™ (Eight-Core) Model 72F3",
    "series": "milan-7003-series",
    "socket": "SP3",
    "cores": 8,
    "threads": 16,
    "category_key": "cpu",
    "sub_category": "amd-server",
    "base_freq": 3.70,
    "boost_freq": 4.10,
    "cache": 256,
    "tdp": 180,
    "tech": "7nm",
    "memory_type": "DDR4",
    "ddr_channels": 8,
    "gen4_lanes": 128,
    "socket_support": "2P/1P",
    "max_memory_size": 4096,
    "packaging": "Tray",
    "image": "/static/images/amd_epyc_72f3.jpg",
    "price":120
  }
]

