cpu_products= [
        {
        "id": "cpu-101",
        "name": "Intel Core i9 (Sample)",
        "price": 189.00,
        "brand": "Intel",
        "category": "Intel Desktop Processor",
        "application": "Desktop",
        "series": "i9",
        "socket": "LGA1700",
        "cores": 24,
        "threads": 32,
        "base_freq": 3.0,
        "cache": 32,
        "tdp": 125,
        "tech": "7nm",
        "memory_type": "DDR5",
        "max_memory_size": 128,
        "packaging": "Boxed",
        "image": "/static/images/amdepyc.jpg"
    },
    {
        "id": "cpu-112",
        "name": "Intel Core i9-13900K",
        "price": 189.00,
        "brand": "Intel",
        "category": "Intel Desktop Processor",
        "application": "Desktop",
        "series": "i9",
        "socket": "LGA1700",
        "cores": 24,
        "threads": 32,
        "base_freq": 3.0,
        "cache": 36,
        "tdp": 125,
        "tech": "7nm",
        "memory_type": "DDR5",
        "max_memory_size": 128,
        "packaging": "Boxed",
        "image": "/static/images/amdepyc.jpg",
        "description": "High-performance gaming and content creation processor"
    },
    {
        "id": "cpu-102",
        "name": "AMD Ryzen 9 7950X",
        "price": 699.00,
        "brand": "AMD",
        "category": "AMD Desktop Processor",
        "application": "Desktop",
        "description": "Powered by next-generation AMD architecture, the 9005 Series Server Processor offers massive multi-threaded performance, high memory bandwidth, and enterprise-grade efficiency for advanced compute workloads.",
        "series": "9005",
        "socket": "AM5",
        "cores": 16,
        "threads": 32,
        "base_freq": 4.5,
        "cache": 64,
        "tdp": 170,
        "tech": "5nm",
        "memory_type": "DDR5",
        "max_memory_size": 128,
        "packaging": "Boxed",
        "image": "/static/images/amdepyc.jpg"
    },
    {
        "id": "cpu-105",
        "name": "Intel Core i5-12400",
        "price": 179.00,
        "brand": "Intel",
        "category": "Intel Desktop Processor",
        "application": "Desktop",
        "series": "i7",
        "socket": "LGA1700",
        "cores": 6,
        "threads": 12,
        "base_freq": 2.5,
        "cache": 18,
        "tdp": 65,
        "tech": "10nm",
        "memory_type": "DDR4",
        "max_memory_size": 128,
        "packaging": "Boxed",
        "image": "/static/images/amdepyc.jpg"
    },
    {
        "id": "cpu-106",
        "name": "AMD Ryzen 5 7600",
        "price": 229.00,
        "brand": "AMD",
        "category": "AMD Desktop Processor",
        "application": "Desktop",
        "description": "Powered by next-generation AMD architecture, the 9005 Series Server Processor offers massive multi-threaded performance, high memory bandwidth, and enterprise-grade efficiency for advanced compute workloads.",
        "series": "9005",
        "socket": "AM5",
        "cores": 6,
        "threads": 12,
        "base_freq": 3.8,
        "cache": 32,
        "tdp": 65,
        "tech": "5nm",
        "memory_type": "DDR5",
        "max_memory_size": 128,
        "packaging": "Boxed",
        "image": "/static/images/amdepyc.jpg"
    },
    {
        "id": "cpu-107",
        "name": "Intel Core i7-12700K",
        "price": 409.00,
        "brand": "Intel",
        "category": "Intel Desktop Processor",
        "application": "Desktop",
        "series": "i7",
        "socket": "LGA1700",
        "cores": 12,
        "threads": 20,
        "base_freq": 3.6,
        "cache": 25,
        "tdp": 125,
        "tech": "10nm",
        "memory_type": "DDR5",
        "max_memory_size": 128,
        "packaging": "Boxed",
        "image": "/static/images/amdepyc.jpg"
    },
    {
        "id": "cpu-109",
        "name": "Intel Core i3-12100",
        "price": 109.00,
        "brand": "Intel",
        "category": "Intel Desktop Processor",
        "application": "Desktop",
        "series": "i7",
        "socket": "LGA1700",
        "cores": 4,
        "threads": 8,
        "base_freq": 3.3,
        "cache": 12,
        "tdp": 60,
        "tech": "10nm",
        "memory_type": "DDR4",
        "max_memory_size": 64,
        "packaging": "Boxed",
        "image": "/static/images/amdepyc.jpg"
    },
    {
        "id": "cpu-110",
        "name": "AMD Ryzen 7 7700X",
        "price": 329.00,
        "brand": "AMD",
        "category": "AMD Desktop Processor",
        "application": "Desktop",
        "description": "Powered by next-generation AMD architecture, the 9005 Series Server Processor offers massive multi-threaded performance, high memory bandwidth, and enterprise-grade efficiency for advanced compute workloads.",
        "series": "9005",
        "socket": "AM5",
        "cores": 8,
        "threads": 16,
        "base_freq": 4.5,
        "cache": 32,
        "tdp": 105,
        "tech": "5nm",
        "memory_type": "DDR5",
        "max_memory_size": 128,
        "packaging": "Boxed",
        "image": "/static/images/amdepyc.jpg"
    },
    
    {
        "id": "cpu-104",
        "name": "AMD EPYC 9654",
        "price": 399.00,
        "brand": "AMD",
        "category": "AMD Server Processor",
        "application": "Server",
        "description": "Powered by next-generation AMD architecture, the 9005 Series Server Processor offers massive multi-threaded performance, high memory bandwidth, and enterprise-grade efficiency for advanced compute workloads.",
        "series": "9005",
        "socket": "SP5",
        "cores": 96,
        "threads": 192,
        "base_freq": 2.7,
        "cache": 384,
        "tdp": 360,
        "tech": "5nm",
        "memory_type": "DDR5",
        "max_memory_size": 2048,
        "packaging": "Tray",
        "image": "/static/images/amdepyc.jpg"
    },
    {
        "id": "cpu-108",
        "name": "AMD Ryzen Threadripper Pro 3995WX",
        "price": 299.00,
        "brand": "AMD",
        "category": "AMD Server Processor",
        "application": "Workstation",
        "description": "Powered by next-generation AMD architecture, the 9005 Series Server Processor offers massive multi-threaded performance, high memory bandwidth, and enterprise-grade efficiency for advanced compute workloads.",
        "series": "9005",
        "socket": "sTRX4",
        "cores": 64,
        "threads": 128,
        "base_freq": 2.7,
        "cache": 256,
        "tdp": 280,
        "tech": "7nm",
        "memory_type": "DDR4",
        "max_memory_size": 2048,
        "packaging": "Tray",
        "image": "/static/images/amdepyc.jpg"
    },

    # // # <!-- ============================ -->
    # // # <!-- EPYC 9005 Series (FULL LIST) -->
    # // # <!-- ============================ -->

    {
        "id": "cpu-epyc-9965",
        "name": "AMD EPYC 9965",
        "brand": "AMD",
        "category": "AMD Server Processor",
        "application": "Server",
        "description": "Powered by next-generation AMD architecture, the 9005 Series Server Processor offers massive multi-threaded performance, high memory bandwidth, and enterprise-grade efficiency for advanced compute workloads.",
        "series": "9005",
        "socket": "SP5",
        "cores": 192,
        "threads": 384,
        "base_freq": 2.25,
        "cache": 384,
        "tdp": 500,
        "tech": "5nm",
        "memory_type": "DDR5",
        "max_memory_size": 6144,
        "packaging": "Tray",
        "image": "/static/images/amdepyc.jpg",
        "price": 11999
    },
    {
        "id": "cpu-epyc-9845",
        "name": "AMD EPYC 9845",
        "brand": "AMD",
        "category": "AMD Server Processor",
        "application": "Server",
        "description": "Powered by next-generation AMD architecture, the 9005 Series Server Processor offers massive multi-threaded performance, high memory bandwidth, and enterprise-grade efficiency for advanced compute workloads.",
        "series": "9005",
        "socket": "SP5",
        "cores": 160,
        "threads": 320,
        "base_freq": 2.1,
        "cache": 320,
        "tdp": 390,
        "tech": "5nm",
        "memory_type": "DDR5",
        "max_memory_size": 6144,
        "packaging": "Tray",
        "image": "/static/images/amdepyc.jpg",
        "price": 9999
    },
    {
        "id": "cpu-epyc-9825",
        "name": "AMD EPYC 9825",
        "brand": "AMD",
        "category": "AMD Server Processor",
        "application": "Server",
        "description": "Powered by next-generation AMD architecture, the 9005 Series Server Processor offers massive multi-threaded performance, high memory bandwidth, and enterprise-grade efficiency for advanced compute workloads.",
        "series": "9005",
        "socket": "SP5",
        "cores": 144,
        "threads": 288,
        "base_freq": 2.2,
        "cache": 384,
        "tdp": 390,
        "tech": "5nm",
        "memory_type": "DDR5",
        "max_memory_size": 6144,
        "packaging": "Tray",
        "image": "/static/images/amdepyc.jpg",
        "price": 9499
    },
    {
        "id": "cpu-epyc-9755",
        "name": "AMD EPYC 9755",
        "brand": "AMD",
        "category": "AMD Server Processor",
        "application": "Server",
        "description": "Powered by next-generation AMD architecture, the 9005 Series Server Processor offers massive multi-threaded performance, high memory bandwidth, and enterprise-grade efficiency for advanced compute workloads.",
        "series": "9005",
        "socket": "SP5",
        "cores": 128,
        "threads": 256,
        "base_freq": 2.7,
        "cache": 512,
        "tdp": 500,
        "tech": "5nm",
        "memory_type": "DDR5",
        "max_memory_size": 6144,
        "packaging": "Tray",
        "image": "/static/images/amdepyc.jpg",
        "price": 8999
    },
    {
        "id": "cpu-epyc-9745",
        "name": "AMD EPYC 9745",
        "brand": "AMD",
        "category": "AMD Server Processor",
        "application": "Server",
        "description": "Powered by next-generation AMD architecture, the 9005 Series Server Processor offers massive multi-threaded performance, high memory bandwidth, and enterprise-grade efficiency for advanced compute workloads.",
        "series": "9005",
        "socket": "SP5",
        "cores": 128,
        "threads": 256,
        "base_freq": 2.4,
        "cache": 256,
        "tdp": 400,
        "tech": "5nm",
        "memory_type": "DDR5",
        "max_memory_size": 4096,
        "packaging": "Tray",
        "image": "/static/images/amdepyc.jpg",
        "price": 8599
    },
    {
        "id": "cpu-epyc-9655",
        "name": "AMD EPYC 9655",
        "brand": "AMD",
        "category": "AMD Server Processor",
        "application": "Server",
        "description": "Powered by next-generation AMD architecture, the 9005 Series Server Processor offers massive multi-threaded performance, high memory bandwidth, and enterprise-grade efficiency for advanced compute workloads.",
        "series": "9005",
        "socket": "SP5",
        "cores": 96,
        "threads": 192,
        "base_freq": 2.6,
        "cache": 384,
        "tdp": 500,
        "tech": "5nm",
        "memory_type": "DDR5",
        "max_memory_size": 4096,
        "packaging": "Tray",
        "image": "/static/images/amdepyc.jpg",
        "price": 7999
    },
    {
        "id": "cpu-epyc-9645",
        "name": "AMD EPYC 9645",
        "brand": "AMD",
        "category": "AMD Server Processor",
        "application": "Server",
        "description": "Powered by next-generation AMD architecture, the 9005 Series Server Processor offers massive multi-threaded performance, high memory bandwidth, and enterprise-grade efficiency for advanced compute workloads.",
        "series": "9005",
        "socket": "SP5",
        "cores": 96,
        "threads": 192,
        "base_freq": 2.4,
        "cache": 256,
        "tdp": 360,
        "tech": "5nm",
        "memory_type": "DDR5",
        "max_memory_size": 4096,
        "packaging": "Tray",
        "image": "/static/images/amdepyc.jpg",
        "price": 7599
    },
    {
        "id": "cpu-epyc-9655p",
        "name": "AMD EPYC 9655P",
        "brand": "AMD",
        "category": "AMD Server Processor",
        "application": "Server",
        "description": "Powered by next-generation AMD architecture, the 9005 Series Server Processor offers massive multi-threaded performance, high memory bandwidth, and enterprise-grade efficiency for advanced compute workloads.",
        "series": "9005",
        "socket": "SP5",
        "cores": 96,
        "threads": 192,
        "base_freq": 2.6,
        "cache": 384,
        "tdp": 500,
        "tech": "5nm",
        "memory_type": "DDR5",
        "max_memory_size": 4096,
        "packaging": "Tray",
        "image": "/static/images/amdepyc.jpg",
        "price": 7499
    },

    {
        "id": "cpu-epyc-9565",
        "name": "AMD EPYC 9565",
        "brand": "AMD",
        "category": "AMD Server Processor",
        "application": "Server",
        "description": "Powered by next-generation AMD architecture, the 9005 Series Server Processor offers massive multi-threaded performance, high memory bandwidth, and enterprise-grade efficiency for advanced compute workloads.",
        "series": "9005",
        "socket": "SP5",
        "cores": 84,
        "threads": 168,
        "base_freq": 2.5,
        "cache": 256,
        "tdp": 400,
        "tech": "5nm",
        "memory_type": "DDR5",
        "max_memory_size": 4096,
        "packaging": "Tray",
        "image": "/static/images/amdepyc.jpg",
        "price": 6999
    },
    {
        "id": "cpu-epyc-9555",
        "name": "AMD EPYC 9555",
        "brand": "AMD",
        "category": "AMD Server Processor",
        "application": "Server",
        "description": "Powered by next-generation AMD architecture, the 9005 Series Server Processor offers massive multi-threaded performance, high memory bandwidth, and enterprise-grade efficiency for advanced compute workloads.",
        "series": "9005",
        "socket": "SP5",
        "cores": 64,
        "threads": 128,
        "base_freq": 2.9,
        "cache": 256,
        "tdp": 360,
        "tech": "5nm",
        "memory_type": "DDR5",
        "max_memory_size": 4096,
        "packaging": "Tray",
        "image": "/static/images/amdepyc.jpg",
        "price": 6499
    },
    {
        "id": "cpu-epyc-9535",
        "name": "AMD EPYC 9535",
        "brand": "AMD",
        "category": "AMD Server Processor",
        "application": "Server",
        "description": "Powered by next-generation AMD architecture, the 9005 Series Server Processor offers massive multi-threaded performance, high memory bandwidth, and enterprise-grade efficiency for advanced compute workloads.",
        "series": "9005",
        "socket": "SP5",
        "cores": 64,
        "threads": 128,
        "base_freq": 2.6,
        "cache": 192,
        "tdp": 320,
        "tech": "5nm",
        "memory_type": "DDR5",
        "max_memory_size": 4096,
        "packaging": "Tray",
        "image": "/static/images/amdepyc.jpg",
        "price": 5999
    },
    {
        "id": "cpu-epyc-9575f",
        "name": "AMD EPYC 9575F",
        "brand": "AMD",
        "category": "AMD Server Processor",
        "application": "Workstation",
        "description": "Powered by next-generation AMD architecture, the 9005 Series Server Processor offers massive multi-threaded performance, high memory bandwidth, and enterprise-grade efficiency for advanced compute workloads.",
        "series": "9005",
        "socket": "SP5",
        "cores": 32,
        "threads": 64,
        "base_freq": 3.8,
        "cache": 256,
        "tdp": 400,
        "tech": "5nm",
        "memory_type": "DDR5",
        "max_memory_size": 2048,
        "packaging": "Tray",
        "image": "/static/images/amdepyc.jpg",
        "price": 6299
    },
    {
        "id": "cpu-epyc-9555p",
        "name": "AMD EPYC 9555P",
        "brand": "AMD",
        "category": "AMD Server Processor",
        "application": "Server",
        "description": "Powered by next-generation AMD architecture, the 9005 Series Server Processor offers massive multi-threaded performance, high memory bandwidth, and enterprise-grade efficiency for advanced compute workloads.",
        "series": "9005",
        "socket": "SP5",
        "cores": 64,
        "threads": 128,
        "base_freq": 2.9,
        "cache": 256,
        "tdp": 360,
        "tech": "5nm",
        "memory_type": "DDR5",
        "max_memory_size": 4096,
        "packaging": "Tray",
        "image": "/static/images/amdepyc.jpg",
        "price": 5799
    },
    {
        "id": "cpu-epyc-9455",
        "name": "AMD EPYC 9455",
        "brand": "AMD",
        "category": "AMD Server Processor",
        "application": "Server",
        "description": "Powered by next-generation AMD architecture, the 9005 Series Server Processor offers massive multi-threaded performance, high memory bandwidth, and enterprise-grade efficiency for advanced compute workloads.",
        "series": "9005",
        "socket": "SP5",
        "cores": 48,
        "threads": 96,
        "base_freq": 2.8,
        "cache": 192,
        "tdp": 300,
        "tech": "5nm",
        "memory_type": "DDR5",
        "max_memory_size": 3072,
        "packaging": "Tray",
        "image": "/static/images/amdepyc.jpg",
        "price": 4999
    },
    {
        "id": "cpu-epyc-9475f",
        "name": "AMD EPYC 9475F",
        "brand": "AMD",
        "category": "AMD Server Processor",
        "application": "Workstation",
        "description": "Powered by next-generation AMD architecture, the 9005 Series Server Processor offers massive multi-threaded performance, high memory bandwidth, and enterprise-grade efficiency for advanced compute workloads.",
        "series": "9005",
        "socket": "SP5",
        "cores": 32,
        "threads": 64,
        "base_freq": 3.6,
        "cache": 256,
        "tdp": 360,
        "tech": "5nm",
        "memory_type": "DDR5",
        "max_memory_size": 2048,
        "packaging": "Tray",
        "image": "/static/images/amdepyc.jpg",
        "price": 5399
    },
    {
        "id": "cpu-epyc-9455p",
        "name": "AMD EPYC 9455P",
        "brand": "AMD",
        "category": "AMD Server Processor",
        "application": "Server",
        "description": "Powered by next-generation AMD architecture, the 9005 Series Server Processor offers massive multi-threaded performance, high memory bandwidth, and enterprise-grade efficiency for advanced compute workloads.",
        "series": "9005",
        "socket": "SP5",
        "cores": 48,
        "threads": 96,
        "base_freq": 2.8,
        "cache": 192,
        "tdp": 300,
        "tech": "5nm",
        "memory_type": "DDR5",
        "max_memory_size": 3072,
        "packaging": "Tray",
        "image": "/static/images/amdepyc.jpg",
        "price": 4699
    },
    {
        "id": "cpu-epyc-9365",
        "name": "AMD EPYC 9365",
        "brand": "AMD",
        "category": "AMD Server Processor",
        "application": "Server",
        "description": "Powered by next-generation AMD architecture, the 9005 Series Server Processor offers massive multi-threaded performance, high memory bandwidth, and enterprise-grade efficiency for advanced compute workloads.",
        "series": "9005",
        "socket": "SP5",
        "cores": 32,
        "threads": 64,
        "base_freq": 3.0,
        "cache": 128,
        "tdp": 280,
        "tech": "5nm",
        "memory_type": "DDR5",
        "max_memory_size": 2048,
        "packaging": "Tray",
        "image": "/static/images/amdepyc.jpg",
        "price": 3999
    },
    {
        "id": "cpu-epyc-9355",
        "name": "AMD EPYC 9355",
        "brand": "AMD",
        "category": "AMD Server Processor",
        "application": "Server",
        "description": "Powered by next-generation AMD architecture, the 9005 Series Server Processor offers massive multi-threaded performance, high memory bandwidth, and enterprise-grade efficiency for advanced compute workloads.",
        "series": "9005",
        "socket": "SP5",
        "cores": 32,
        "threads": 64,
        "base_freq": 2.8,
        "cache": 128,
        "tdp": 260,
        "tech": "5nm",
        "memory_type": "DDR5",
        "max_memory_size": 2048,
        "packaging": "Tray",
        "image": "/static/images/amdepyc.jpg",
        "price": 3799
    },
    {
        "id": "cpu-epyc-9335",
        "name": "AMD EPYC 9335",
        "brand": "AMD",
        "category": "AMD Server Processor",
        "application": "Server",
        "description": "Powered by next-generation AMD architecture, the 9005 Series Server Processor offers massive multi-threaded performance, high memory bandwidth, and enterprise-grade efficiency for advanced compute workloads.",
        "series": "9005",
        "socket": "SP5",
        "cores": 32,
        "threads": 64,
        "base_freq": 2.6,
        "cache": 128,
        "tdp": 240,
        "tech": "5nm",
        "memory_type": "DDR5",
        "max_memory_size": 2048,
        "packaging": "Tray",
        "image": "/static/images/amdepyc.jpg",
        "price": 3399
    },
    {
        "id": "cpu-epyc-9375f",
        "name": "AMD EPYC 9375F",
        "brand": "AMD",
        "category": "AMD Server Processor",
        "application": "Workstation",
        "description": "Powered by next-generation AMD architecture, the 9005 Series Server Processor offers massive multi-threaded performance, high memory bandwidth, and enterprise-grade efficiency for advanced compute workloads.",
        "series": "9005",
        "socket": "SP5",
        "cores": 16,
        "threads": 32,
        "base_freq": 4.0,
        "cache": 128,
        "tdp": 320,
        "tech": "5nm",
        "memory_type": "DDR5",
        "max_memory_size": 1024,
        "packaging": "Tray",
        "image": "/static/images/amdepyc.jpg",
        "price": 3499
    },
    {
        "id": "cpu-epyc-9355p",
        "name": "AMD EPYC 9355P",
        "brand": "AMD",
        "category": "AMD Server Processor",
        "application": "Server",
        "description": "Powered by next-generation AMD architecture, the 9005 Series Server Processor offers massive multi-threaded performance, high memory bandwidth, and enterprise-grade efficiency for advanced compute workloads.",
        "series": "9005",
        "socket": "SP5",
        "cores": 32,
        "threads": 64,
        "base_freq": 2.8,
        "cache": 128,
        "tdp": 260,
        "tech": "5nm",
        "memory_type": "DDR5",
        "max_memory_size": 2048,
        "packaging": "Tray",
        "image": "/static/images/amdepyc.jpg",
        "price": 3599
    },
    {
        "id": "cpu-epyc-9255",
        "name": "AMD EPYC 9255",
        "brand": "AMD",
        "category": "AMD Server Processor",
        "application": "Server",
        "description": "Powered by next-generation AMD architecture, the 9005 Series Server Processor offers massive multi-threaded performance, high memory bandwidth, and enterprise-grade efficiency for advanced compute workloads.",
        "series": "9005",
        "socket": "SP5",
        "cores": 24,
        "threads": 48,
        "base_freq": 2.7,
        "cache": 96,
        "tdp": 200,
        "tech": "5nm",
        "memory_type": "DDR5",
        "max_memory_size": 1536,
        "packaging": "Tray",
        "image": "/static/images/amdepyc.jpg",
        "price": 2999
    },
    {
        "id": "cpu-epyc-9275f",
        "name": "AMD EPYC 9275F",
        "brand": "AMD",
        "category": "AMD Server Processor",
        "application": "Workstation",
        "description": "Powered by next-generation AMD architecture, the 9005 Series Server Processor offers massive multi-threaded performance, high memory bandwidth, and enterprise-grade efficiency for advanced compute workloads.",
        "series": "9005",
        "socket": "SP5",
        "cores": 24,
        "threads": 48,
        "base_freq": 3.5,
        "cache": 192,
        "tdp": 260,
        "tech": "5nm",
        "memory_type": "DDR5",
        "max_memory_size": 1536,
        "packaging": "Tray",
        "image": "/static/images/amdepyc.jpg",
        "price": 3299
    },
    {
        "id": "cpu-epyc-9135",
        "name": "AMD EPYC 9135",
        "brand": "AMD",
        "category": "AMD Server Processor",
        "application": "Server",
        "series": "9005",
        "description": "Powered by next-generation AMD architecture, the 9005 Series Server Processor offers massive multi-threaded performance, high memory bandwidth, and enterprise-grade efficiency for advanced compute workloads.",
        "socket": "SP5",
        "cores": 16,
        "threads": 32,
        "base_freq": 2.8,
        "cache": 64,
        "tdp": 200,
        "tech": "5nm",
        "memory_type": "DDR5",
        "max_memory_size": 1024,
        "packaging": "Tray",
        "image": "/static/images/amdepyc.jpg",
        "price": 2199
    },
    {
        "id": "cpu-epyc-9115",
        "name": "AMD EPYC 9115",
        "brand": "AMD",
        "category": "AMD Server Processor",
        "application": "Server",
        "description": "Powered by next-generation AMD architecture, the 9005 Series Server Processor offers massive multi-threaded performance, high memory bandwidth, and enterprise-grade efficiency for advanced compute workloads.",
        "series": "9005",
        "socket": "SP5",
        "cores": 16,
        "threads": 32,
        "base_freq": 2.5,
        "cache": 64,
        "tdp": 180,
        "tech": "5nm",
        "memory_type": "DDR5",
        "max_memory_size": 1024,
        "packaging": "Tray",
        "image": "/static/images/amdepyc.jpg",
        "price": 1999
    },
    {
        "id": "cpu-epyc-9175f",
        "name": "AMD EPYC 9175F",
        "brand": "AMD",
        "category": "AMD Server Processor",
        "application": "Workstation",
        "description": "Powered by next-generation AMD architecture, the 9005 Series Server Processor offers massive multi-threaded performance, high memory bandwidth, and enterprise-grade efficiency for advanced compute workloads.",
        "series": "9005",
        "socket": "SP5",
        "cores": 16,
        "threads": 32,
        "base_freq": 4.0,
        "cache": 128,
        "tdp": 300,
        "tech": "5nm",
        "memory_type": "DDR5",
        "max_memory_size": 1024,
        "packaging": "Tray",
        "image": "/static/images/amdepyc.jpg",
        "price": 2599
    },
    {
        "id": "cpu-epyc-9015",
        "name": "AMD EPYC 9015",
        "brand": "AMD",
        "category": "AMD Server Processor",
        "application": "Server",
        "description": "Powered by next-generation AMD architecture, the 9005 Series Server Processor offers massive multi-threaded performance, high memory bandwidth, and enterprise-grade efficiency for advanced compute workloads.",
        "series": "9005",
        "socket": "SP5",
        "cores": 8,
        "threads": 16,
        "base_freq": 2.7,
        "cache": 32,
        "tdp": 150,
        "tech": "5nm",
        "memory_type": "DDR5",
        "max_memory_size": 1024,
        "packaging": "Tray",
        "image": "/static/images/amdepyc.jpg",
        "price": 1499
    },
    {
        "id": "cpu-101",
        "name": "Intel Core i9-13900K",
        "price": 189.00,
        "brand": "Intel",
        "category": "Intel Desktop Processor",
        "application": "Gaming",
        "series": "i7",
        "socket": "LGA1700",
        "cores": 24,
        "threads": 32,
        "base_freq": 3.0,
        "cache": 36,
        "tdp": 125,
        "tech": "7nm",
        "memory_type": "DDR5",
        "max_memory_size": 128,
        "packaging": "Boxed",
        "image": "/static/images/amdepyc.jpg",
        "description": "High-performance gaming CPU"
    },
    {
        "id": "cpu-112",
        "name": "Intel Core i9-13900K",
        "price": 189.00,
        "brand": "Intel",
        "category": "Intel Desktop Processor",
        "application": "Gaming",
        "series": "i7",
        "socket": "LGA1700",
        "cores": 24,
        "threads": 32,
        "base_freq": 3.0,
        "cache": 36,
        "tdp": 125,
        "tech": "7nm",
        "memory_type": "DDR5",
        "max_memory_size": 128,
        "packaging": "Boxed",
        "image": "/static/images/amdepyc.jpg",
        "description": "High-performance gaming and content creation processor"
    },
    {
        "id": "cpu-103",
        "name": "Intel Xeon Silver 4314",
        "price": 550.00,
        "brand": "Intel",
        "category": "Intel Server Processor",
        "application": "Server",
        "series": "i7",
        "socket": "LGA4677",
        "cores": 16,
        "threads": 32,
        "base_freq": 2.4,
        "cache": 30,
        "tdp": 105,
        "tech": "10nm",
        "memory_type": "DDR5",
        "max_memory_size": 512,
        "packaging": "Tray",
        "image": "/static/images/amdepyc.jpg"
    },
    {
        "id": "cpu-105",
        "name": "Intel Core i5-12400",
        "price": 179.00,
        "brand": "Intel",
        "category": "Intel Desktop Processor",
        "application": "Desktop",
        "series": "i7",
        "socket": "LGA1700",
        "cores": 6,
        "threads": 12,
        "base_freq": 2.5,
        "cache": 18,
        "tdp": 65,
        "tech": "10nm",
        "memory_type": "DDR4",
        "max_memory_size": 128,
        "packaging": "Boxed",
        "image": "/static/images/amdepyc.jpg"
    },
    {
        "id": "cpu-107",
        "name": "Intel Core i7-12700K",
        "price": 409.00,
        "brand": "Intel",
        "category": "Intel Desktop Processor",
        "application": "Gaming",
        "series": "i7",
        "socket": "LGA1700",
        "cores": 12,
        "threads": 20,
        "base_freq": 3.6,
        "cache": 25,
        "tdp": 125,
        "tech": "10nm",
        "memory_type": "DDR5",
        "max_memory_size": 128,
        "packaging": "Boxed",
        "image": "/static/images/amdepyc.jpg"
    },
    {
        "id": "cpu-109",
        "name": "Intel Core i3-12100",
        "price": 109.00,
        "brand": "Intel",
        "series": "i7",
        "category": "Intel Desktop Processor",
        "application": "Desktop",
        "socket": "LGA1700",
        "cores": 4,
        "threads": 8,
        "base_freq": 3.3,
        "cache": 12,
        "tdp": 60,
        "tech": "10nm",
        "memory_type": "DDR4",
        "max_memory_size": 64,
        "packaging": "Boxed",
        "image": "/static/images/amdepyc.jpg"
    },
    
    #9004
    {
    "id": "cpu-epyc-9654p",
    "name": "AMD EPYC 9654P",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "Powered by next-generation AMD “Zen 4” architecture, this 9004 Series server processor delivers extreme core density, high memory bandwidth, and enterprise-grade efficiency for large-scale compute and virtualized workloads.",
    "series": "9004",
    "socket": "SP5",
    "cores": 96,
    "threads": 192,
    "base_freq": 2.4,
    "cache": 384,
    "tdp": 360,
    "tech": "5nm",
    "memory_type": "DDR5",
    "max_memory_size": 6144,
    "packaging": "Tray",
    "image": "/static/images/amdepyc.jpg",
    "price": 6500
  },
  {
    "id": "cpu-epyc-9554p",
    "name": "AMD EPYC 9554P",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "High-core-count EPYC 9004 Series processor designed for dense virtualization, cloud infrastructure, and mixed enterprise workloads with excellent performance-per-watt.",
    "series": "9004",
    "socket": "SP5",
    "cores": 64,
    "threads": 128,
    "base_freq": 3.1,
    "cache": 256,
    "tdp": 360,
    "tech": "5nm",
    "memory_type": "DDR5",
    "max_memory_size": 6144,
    "packaging": "Tray",
    "image": "/static/images/amdepyc.jpg",
    "price": 4000
  },
  {
    "id": "cpu-epyc-9454p",
    "name": "AMD EPYC 9454P",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "48-core EPYC 9004 Series CPU balancing high throughput and efficiency, ideal for database, analytics, and general-purpose enterprise compute.",
    "series": "9004",
    "socket": "SP5",
    "cores": 48,
    "threads": 96,
    "base_freq": 2.75,
    "cache": 256,
    "tdp": 290,
    "tech": "5nm",
    "memory_type": "DDR5",
    "max_memory_size": 6144,
    "packaging": "Tray",
    "image": "/static/images/amdepyc.jpg",
    "price": 3200
  },
  {
    "id": "cpu-epyc-9474f",
    "name": "AMD EPYC 9474F",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "Frequency-optimized EPYC 9004F processor delivering high per-core performance and low latency for trading, in-memory databases, and latency-sensitive workloads.",
    "series": "9004",
    "socket": "SP5",
    "cores": 48,
    "threads": 96,
    "base_freq": 3.6,
    "cache": 256,
    "tdp": 360,
    "tech": "5nm",
    "memory_type": "DDR5",
    "max_memory_size": 6144,
    "packaging": "Tray",
    "image": "/static/images/amdepyc.jpg",
    "price": 4500
  },
  {
    "id": "cpu-epyc-9334",
    "name": "AMD EPYC 9334",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "32-core EPYC 9004 Series CPU tuned for balanced performance and efficiency across cloud, microservices, and scale-out infrastructure.",
    "series": "9004",
    "socket": "SP5",
    "cores": 32,
    "threads": 64,
    "base_freq": 2.7,
    "cache": 128,
    "tdp": 210,
    "tech": "5nm",
    "memory_type": "DDR5",
    "max_memory_size": 6144,
    "packaging": "Tray",
    "image": "/static/images/amdepyc.jpg",
    "price": 2100
  },
  {
    "id": "cpu-epyc-9354p",
    "name": "AMD EPYC 9354P",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "Single-socket optimized 32-core EPYC 9004 processor offering strong performance for virtualized environments and dense edge or branch deployments.",
    "series": "9004",
    "socket": "SP5",
    "cores": 32,
    "threads": 64,
    "base_freq": 3.25,
    "cache": 256,
    "tdp": 280,
    "tech": "5nm",
    "memory_type": "DDR5",
    "max_memory_size": 6144,
    "packaging": "Tray",
    "image": "/static/images/amdepyc.jpg",
    "price": 2450
  },
  {
    "id": "cpu-epyc-9374f",
    "name": "AMD EPYC 9374F",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "High-frequency 32-core EPYC 9004F CPU designed for per-core licensed workloads, SQL databases, and latency-critical enterprise applications.",
    "series": "9004",
    "socket": "SP5",
    "cores": 32,
    "threads": 64,
    "base_freq": 3.85,
    "cache": 256,
    "tdp": 320,
    "tech": "5nm",
    "memory_type": "DDR5",
    "max_memory_size": 6144,
    "packaging": "Tray",
    "image": "/static/images/amdepyc.jpg",
    "price": 3500
  },
  {
    "id": "cpu-epyc-9254",
    "name": "AMD EPYC 9254",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "24-core EPYC 9004 Series processor with strong multi-threaded performance for mid-range servers, line-of-business apps, and infrastructure services.",
    "series": "9004",
    "socket": "SP5",
    "cores": 24,
    "threads": 48,
    "base_freq": 2.9,
    "cache": 128,
    "tdp": 200,
    "tech": "5nm",
    "memory_type": "DDR5",
    "max_memory_size": 6144,
    "packaging": "Tray",
    "image": "/static/images/amdepyc.jpg",
    "price": 2300
  },
  {
    "id": "cpu-epyc-9224",
    "name": "AMD EPYC 9224",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "Value-optimized 24-core EPYC 9004 processor ideal for entry enterprise servers, scale-out services, and cost-sensitive deployments.",
    "series": "9004",
    "socket": "SP5",
    "cores": 24,
    "threads": 48,
    "base_freq": 2.5,
    "cache": 64,
    "tdp": 200,
    "tech": "5nm",
    "memory_type": "DDR5",
    "max_memory_size": 6144,
    "packaging": "Tray",
    "image": "/static/images/amdepyc.jpg",
    "price": 1800
  },
  {
    "id": "cpu-epyc-9274f",
    "name": "AMD EPYC 9274F",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "Frequency-tuned 24-core EPYC 9004F processor optimized for per-core licensing, transactional databases, and high-frequency trading systems.",
    "series": "9004",
    "socket": "SP5",
    "cores": 24,
    "threads": 48,
    "base_freq": 4.05,
    "cache": 256,
    "tdp": 320,
    "tech": "5nm",
    "memory_type": "DDR5",
    "max_memory_size": 6144,
    "packaging": "Tray",
    "image": "/static/images/amdepyc.jpg",
    "price": 2950
  },
  {
    "id": "cpu-epyc-9124",
    "name": "AMD EPYC 9124",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "16-core EPYC 9004 Series CPU for entry servers, control planes, and lightweight virtualization with solid performance and efficiency.",
    "series": "9004",
    "socket": "SP5",
    "cores": 16,
    "threads": 32,
    "base_freq": 3.0,
    "cache": 64,
    "tdp": 200,
    "tech": "5nm",
    "memory_type": "DDR5",
    "max_memory_size": 6144,
    "packaging": "Tray",
    "image": "/static/images/amdepyc.jpg",
    "price": 1800
  },
  {
    "id": "cpu-epyc-9174f",
    "name": "AMD EPYC 9174F",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "High-frequency 16-core EPYC 9004F CPU delivering top per-core performance for low-latency applications, financial services, and real-time analytics.",
    "series": "9004",
    "socket": "SP5",
    "cores": 16,
    "threads": 32,
    "base_freq": 4.1,
    "cache": 256,
    "tdp": 320,
    "tech": "5nm",
    "memory_type": "DDR5",
    "max_memory_size": 6144,
    "packaging": "Tray",
    "image": "/static/images/amdepyc.jpg",
    "price": 2600
  },
  {
    "id": "cpu-epyc-9684x",
    "name": "AMD EPYC 9684X",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "Flagship EPYC 9004X processor with AMD 3D V-Cache technology, combining 96 cores and massive L3 cache for HPC, CAE/CFD, and large-scale simulation workloads.",
    "series": "9004",
    "socket": "SP5",
    "cores": 96,
    "threads": 192,
    "base_freq": 2.55,
    "cache": 1152,
    "tdp": 400,
    "tech": "5nm",
    "memory_type": "DDR5",
    "max_memory_size": 6144,
    "packaging": "Tray",
    "image": "/static/images/amdepyc.jpg",
    "price": 9000
  },
  {
    "id": "cpu-epyc-9384x",
    "name": "AMD EPYC 9384X",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "32-core EPYC 9004X with 3D V-Cache, delivering huge L3 capacity and strong frequency for EDA, FEA, and memory-bound technical workloads.",
    "series": "9004",
    "socket": "SP5",
    "cores": 32,
    "threads": 64,
    "base_freq": 3.1,
    "cache": 768,
    "tdp": 320,
    "tech": "5nm",
    "memory_type": "DDR5",
    "max_memory_size": 6144,
    "packaging": "Tray",
    "image": "/static/images/amdepyc.jpg",
    "price": 6500
  },
  {
    "id": "cpu-epyc-9184x",
    "name": "AMD EPYC 9184X",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "16-core EPYC 9004X processor with 3D V-Cache, blending high per-core performance and massive L3 cache for specialized technical and EDA workloads.",
    "series": "9004",
    "socket": "SP5",
    "cores": 16,
    "threads": 32,
    "base_freq": 3.55,
    "cache": 768,
    "tdp": 320,
    "tech": "5nm",
    "memory_type": "DDR5",
    "max_memory_size": 6144,
    "packaging": "Tray",
    "image": "/static/images/amdepyc.jpg",
    "price": 3750
  },
  
  #7003
  
  {
"id":"cpu-epyc-7203",
"name":"AMD EPYC 7203",
"brand":"AMD",
"category":"AMD Server Processor",
"application":"Server",
"description":"Entry-level AMD EPYC 7003 processor designed for efficient cloud computing, edge deployments, and lightweight virtualized workloads.",
"series":"7003",
"socket":"SP3",
"cores":8,"threads":16,"base_freq":2.3,"cache":64,"tdp":120,
"tech":"7nm","memory_type":"DDR4","max_memory_size":4096,
"packaging":"Tray","image":"/static/images/amd-epyc-series.jpeg","price":750
},

{
"id":"cpu-epyc-7303",
"name":"AMD EPYC 7303",
"brand":"AMD","category":"AMD Server Processor","application":"Server",
"description":"16-core EPYC 7303 optimized for balanced enterprise performance, virtual machines, and scale-out infrastructure.",
"series":"7003","socket":"SP3",
"cores":16,"threads":32,"base_freq":2.4,"cache":128,"tdp":155,
"tech":"7nm","memory_type":"DDR4","max_memory_size":4096,
"packaging":"Tray","image":"/static/images/amd-epyc-series.jpeg","price":1300
},

{
"id":"cpu-epyc-7313",
"name":"AMD EPYC 7313",
"brand":"AMD","category":"AMD Server Processor","application":"Server",
"description":"Balanced 16-core EPYC 7313 processor ideal for virtualization, application hosting, and business-critical cloud services.",
"series":"7003","socket":"SP3",
"cores":16,"threads":32,"base_freq":3.0,"cache":128,"tdp":155,
"tech":"7nm","memory_type":"DDR4","max_memory_size":4096,
"packaging":"Tray","image":"/static/images/amd-epyc-series.jpeg","price":1100
},

{
"id":"cpu-epyc-7343",
"name":"AMD EPYC 7343",
"brand":"AMD","category":"AMD Server Processor","application":"Server",
"description":"High-efficiency 16-core EPYC 7343 built for enterprise servers and dense compute nodes.",
"series":"7003","socket":"SP3",
"cores":16,"threads":32,"base_freq":3.2,"cache":128,"tdp":190,
"tech":"7nm","memory_type":"DDR4","max_memory_size":4096,
"packaging":"Tray","image":"/static/images/amd-epyc-series.jpeg","price":1650
},

{
"id":"cpu-epyc-7413",
"name":"AMD EPYC 7413",
"brand":"AMD","category":"AMD Server Processor","application":"Server",
"description":"24-core EPYC designed for cloud workloads, business analytics, and heavy multitasking.",
"series":"7003","socket":"SP3",
"cores":24,"threads":48,"base_freq":2.65,"cache":128,"tdp":180,
"tech":"7nm","memory_type":"DDR4","max_memory_size":4096,
"packaging":"Tray","image":"/static/images/amd-epyc-series.jpeg","price":2000
},

{
"id":"cpu-epyc-7443",
"name":"AMD EPYC 7443",
"brand":"AMD","category":"AMD Server Processor","application":"Server",
"description":"24-core enterprise-grade CPU optimized for virtualization and hybrid cloud workloads.",
"series":"7003","socket":"SP3",
"cores":24,"threads":48,"base_freq":2.85,"cache":128,"tdp":200,
"tech":"7nm","memory_type":"DDR4","max_memory_size":4096,
"packaging":"Tray","image":"/static/images/amd-epyc-series.jpeg","price":2250
},

{
"id":"cpu-epyc-7713",
"name":"AMD EPYC 7713",
"brand":"AMD","category":"AMD Server Processor","application":"Server",
"description":"64-core high-density compute processor built for hyperscale cloud and virtualization platforms.",
"series":"7003","socket":"SP3",
"cores":64,"threads":128,"base_freq":2.0,"cache":256,"tdp":225,
"tech":"7nm","memory_type":"DDR4","max_memory_size":4096,
"packaging":"Tray","image":"/static/images/amd-epyc-series.jpeg","price":6000
},

{
"id":"cpu-epyc-7763",
"name":"AMD EPYC 7763",
"brand":"AMD","category":"AMD Server Processor","application":"Server",
"description":"Flagship 64-core EPYC processor for enterprise cloud, AI inference, and advanced analytics.",
"series":"7003","socket":"SP3",
"cores":64,"threads":128,"base_freq":2.45,"cache":256,"tdp":280,
"tech":"7nm","memory_type":"DDR4","max_memory_size":4096,
"packaging":"Tray","image":"/static/images/amd-epyc-series.jpeg","price":7900
},

{
"id":"cpu-epyc-7203p",
"name":"AMD EPYC 7203P",
"brand":"AMD","category":"AMD Server Processor","application":"Server",
"description":"Single-socket optimized entry EPYC CPU for branch servers and lightweight enterprise workloads.",
"series":"7003","socket":"SP3",
"cores":8,"threads":16,"base_freq":2.3,"cache":64,"tdp":120,
"tech":"7nm","memory_type":"DDR4","max_memory_size":4096,
"packaging":"Tray","image":"/static/images/amd-epyc-series.jpeg","price":720
},

{
"id":"cpu-epyc-72f3",
"name":"AMD EPYC 72F3",
"brand":"AMD","category":"AMD Server Processor","application":"Server",
"description":"Frequency optimized EPYC CPU built for per-core licensed software and low-latency workloads.",
"series":"7003","socket":"SP3",
"cores":8,"threads":16,"base_freq":3.7,"cache":256,"tdp":180,
"tech":"7nm","memory_type":"DDR4","max_memory_size":4096,
"packaging":"Tray","image":"/static/images/amd-epyc-series.jpeg","price":2700
},

{
"id":"cpu-epyc-7303p",
"name":"AMD EPYC 7303P",
"brand":"AMD","category":"AMD Server Processor","application":"Server",
"description":"Single socket performance CPU for cost-effective high throughput enterprise workloads.",
"series":"7003","socket":"SP3",
"cores":16,"threads":32,"base_freq":2.4,"cache":128,"tdp":155,
"tech":"7nm","memory_type":"DDR4","max_memory_size":4096,
"packaging":"Tray","image":"/static/images/amd-epyc-series.jpeg","price":1250
},

{
"id":"cpu-epyc-7313p",
"name":"AMD EPYC 7313P",
"brand":"AMD","category":"AMD Server Processor","application":"Server",
"description":"High-efficiency single socket EPYC processor for business servers.",
"series":"7003","socket":"SP3",
"cores":16,"threads":32,"base_freq":3.0,"cache":128,"tdp":155,
"tech":"7nm","memory_type":"DDR4","max_memory_size":4096,
"packaging":"Tray","image":"/static/images/amd-epyc-series.jpeg","price":1050
},

{
"id":"cpu-epyc-73f3",
"name":"AMD EPYC 73F3",
"brand":"AMD","category":"AMD Server Processor","application":"Server",
"description":"High-frequency EPYC CPU tailored for latency-sensitive and licensed enterprise workloads.",
"series":"7003","socket":"SP3",
"cores":16,"threads":32,"base_freq":3.5,"cache":256,"tdp":240,
"tech":"7nm","memory_type":"DDR4","max_memory_size":4096,
"packaging":"Tray","image":"/static/images/amd-epyc-series.jpeg","price":3900
},

{
"id":"cpu-epyc-7443p",
"name":"AMD EPYC 7443P",
"brand":"AMD","category":"AMD Server Processor","application":"Server",
"description":"Single socket powerhouse for virtualization, mid-tier databases, and cloud workloads.",
"series":"7003","socket":"SP3",
"cores":24,"threads":48,"base_freq":2.85,"cache":128,"tdp":200,
"tech":"7nm","memory_type":"DDR4","max_memory_size":4096,
"packaging":"Tray","image":"/static/images/amd-epyc-series.jpeg","price":1400
},

{
"id":"cpu-epyc-74f3",
"name":"AMD EPYC 74F3",
"brand":"AMD","category":"AMD Server Processor","application":"Server",
"description":"24-core frequency-optimized CPU for financial, ERP, and mission critical systems.",
"series":"7003","socket":"SP3",
"cores":24,"threads":48,"base_freq":3.2,"cache":256,"tdp":240,
"tech":"7nm","memory_type":"DDR4","max_memory_size":4096,
"packaging":"Tray","image":"/static/images/amd-epyc-series.jpeg","price":4200
},

{
"id":"cpu-epyc-7543p",
"name":"AMD EPYC 7543P",
"brand":"AMD","category":"AMD Server Processor","application":"Server",
"description":"High core density single socket server CPU for virtualization and multi-tenant platforms.",
"series":"7003","socket":"SP3",
"cores":32,"threads":64,"base_freq":2.8,"cache":256,"tdp":225,
"tech":"7nm","memory_type":"DDR4","max_memory_size":4096,
"packaging":"Tray","image":"/static/images/amd-epyc-series.jpeg","price":3050
},

{
"id":"cpu-epyc-75f3",
"name":"AMD EPYC 75F3",
"brand":"AMD","category":"AMD Server Processor","application":"Server",
"description":"Performance tuned frequency server CPU ideal for licensed enterprise software.",
"series":"7003","socket":"SP3",
"cores":32,"threads":64,"base_freq":2.95,"cache":256,"tdp":280,
"tech":"7nm","memory_type":"DDR4","max_memory_size":4096,
"packaging":"Tray","image":"/static/images/amd-epyc-series.jpeg","price":5000
},

{
"id":"cpu-epyc-7643p",
"name":"AMD EPYC 7643P",
"brand":"AMD","category":"AMD Server Processor","application":"Server",
"description":"High-performance single socket compute processor built for demanding enterprise workloads.",
"series":"7003","socket":"SP3",
"cores":48,"threads":96,"base_freq":2.3,"cache":256,"tdp":240,
"tech":"7nm","memory_type":"DDR4","max_memory_size":4096,
"packaging":"Tray","image":"/static/images/amd-epyc-series.jpeg","price":5200
},

{
"id":"cpu-epyc-7663p",
"name":"AMD EPYC 7663P",
"brand":"AMD","category":"AMD Server Processor","application":"Server",
"description":"Extreme single socket performance processor for large virtualization clusters.",
"series":"7003","socket":"SP3",
"cores":56,"threads":112,"base_freq":2.0,"cache":256,"tdp":240,
"tech":"7nm","memory_type":"DDR4","max_memory_size":4096,
"packaging":"Tray","image":"/static/images/amd-epyc-series.jpeg","price":6000
},

{
"id":"cpu-epyc-7713p",
"name":"AMD EPYC 7713P",
"brand":"AMD","category":"AMD Server Processor","application":"Server",
"description":"64-core single-socket monster built for hyperscale workloads.",
"series":"7003","socket":"SP3",
"cores":64,"threads":128,"base_freq":2.0,"cache":256,"tdp":225,
"tech":"7nm","memory_type":"DDR4","max_memory_size":4096,
"packaging":"Tray","image":"/static/images/amd-epyc-series.jpeg","price":5550
},

{
"id":"cpu-epyc-7373x",
"name":"AMD EPYC 7373X",
"brand":"AMD","category":"AMD Server Processor","application":"Server",
"description":"3D V-Cache enhanced EPYC built for HPC and memory-bound workloads.",
"series":"7003","socket":"SP3",
"cores":16,"threads":32,"base_freq":3.05,"cache":768,"tdp":240,
"tech":"7nm","memory_type":"DDR4","max_memory_size":4096,
"packaging":"Tray","image":"/static/images/amd-epyc-series.jpeg","price":4200
},

{
"id":"cpu-epyc-7473x",
"name":"AMD EPYC 7473X",
"brand":"AMD","category":"AMD Server Processor","application":"Server",
"description":"24-core Milan-X CPU with massive cache for CAE, CFD and scientific workloads.",
"series":"7003","socket":"SP3",
"cores":24,"threads":48,"base_freq":2.8,"cache":768,"tdp":240,
"tech":"7nm","memory_type":"DDR4","max_memory_size":4096,
"packaging":"Tray","image":"/static/images/amd-epyc-series.jpeg","price":4800
},

{
"id":"cpu-epyc-7773x",
"name":"AMD EPYC 7773X",
"brand":"AMD","category":"AMD Server Processor","application":"Server",
"description":"Top-tier Milan-X processor with 3D V-Cache for HPC and simulation environments.",
"series":"7003","socket":"SP3",
"cores":64,"threads":128,"base_freq":2.2,"cache":768,"tdp":280,
"tech":"7nm","memory_type":"DDR4","max_memory_size":4096,
"packaging":"Tray","image":"/static/images/amd-epyc-series.jpeg","price":9500
},

  {
    "id": "cpu-epyc-8534p",
    "name": "AMD EPYC 8534P",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "64-core 4th Gen AMD EPYC 8004 (Siena) single-socket CPU designed for dense cloud, storage, and edge servers with strong efficiency and throughput.",
    "series": "8004",
    "socket": "SP6",
    "cores": 64,
    "threads": 128,
    "base_freq": 2.3,
    "cache": 128,
    "tdp": 200,
    "tech": "5nm",
    "memory_type": "DDR5",
    "max_memory_size": 4800,
    "packaging": "Tray",
    "image": "/static/images/amd-epyc-series.jpeg",
    "price": 5800
  },
  {
    "id": "cpu-epyc-8534pn",
    "name": "AMD EPYC 8534PN",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server / Telco / Edge",
    "description": "64-core EPYC 8534PN tuned for telco and edge with lower TDP and efficient performance for NEBS-style platforms.",
    "series": "8004",
    "socket": "SP6",
    "cores": 64,
    "threads": 128,
    "base_freq": 2.0,
    "cache": 128,
    "tdp": 175,
    "tech": "5nm",
    "memory_type": "DDR5",
    "max_memory_size": 4800,
    "packaging": "Tray",
    "image": "/static/images/amd-epyc-series.jpeg",
    "price": 6100
  },

  {
    "id": "cpu-epyc-8434p",
    "name": "AMD EPYC 8434P",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "48-core single-socket EPYC 8434P delivering high core density and strong memory bandwidth for mid-to-high tier cloud and virtualization workloads.",
    "series": "8004",
    "socket": "SP6",
    "cores": 48,
    "threads": 96,
    "base_freq": 2.5,
    "cache": 128,
    "tdp": 200,
    "tech": "5nm",
    "memory_type": "DDR5",
    "max_memory_size": 4800,
    "packaging": "Tray",
    "image": "/static/images/amd-epyc-series.jpeg",
    "price": 5200
  },
  {
    "id": "cpu-epyc-8434pn",
    "name": "AMD EPYC 8434PN",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server / Telco / Edge",
    "description": "48-core EPYC 8434PN variant optimized for telco, edge, and NEBS platforms with reduced TDP and efficient performance-per-watt.",
    "series": "8004",
    "socket": "SP6",
    "cores": 48,
    "threads": 96,
    "base_freq": 2.0,
    "cache": 128,
    "tdp": 155,
    "tech": "5nm",
    "memory_type": "DDR5",
    "max_memory_size": 4800,
    "packaging": "Tray",
    "image": "/static/images/amd-epyc-series.jpeg",
    "price": 5400
  },
  {
    "id": "cpu-epyc-8324p",
    "name": "AMD EPYC 8324P",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "32-core EPYC 8324P offering a sweet spot of core count and efficiency for general-purpose cloud, virtualization, and storage nodes.",
    "series": "8004",
    "socket": "SP6",
    "cores": 32,
    "threads": 64,
    "base_freq": 2.65,
    "cache": 128,
    "tdp": 180,
    "tech": "5nm",
    "memory_type": "DDR5",
    "max_memory_size": 4800,
    "packaging": "Tray",
    "image": "/static/images/amd-epyc-series.jpeg",
    "price": 3600
  },
  {
    "id": "cpu-epyc-8324pn",
    "name": "AMD EPYC 8324PN",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server / Telco / Edge",
    "description": "32-core EPYC 8324PN with lower base clock and TDP, ideal for power-sensitive telco, edge, and networking infrastructure.",
    "series": "8004",
    "socket": "SP6",
    "cores": 32,
    "threads": 64,
    "base_freq": 2.05,
    "cache": 128,
    "tdp": 130,
    "tech": "5nm",
    "memory_type": "DDR5",
    "max_memory_size": 4800,
    "packaging": "Tray",
    "image": "/static/images/amd-epyc-series.jpeg",
    "price": 3400
  },

  {
    "id": "cpu-epyc-8224p",
    "name": "AMD EPYC 8224P",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "24-core EPYC 8224P server CPU tuned for efficient performance in compact single-socket servers and mixed workloads.",
    "series": "8004",
    "socket": "SP6",
    "cores": 24,
    "threads": 48,
    "base_freq": 2.55,
    "cache": 64,
    "tdp": 160,
    "tech": "5nm",
    "memory_type": "DDR5",
    "max_memory_size": 4800,
    "packaging": "Tray",
    "image": "/static/images/amd-epyc-series.jpeg",
    "price": 2600
  },

  {
    "id": "cpu-epyc-8224pn",
    "name": "AMD EPYC 8224PN",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server / Telco / Edge",
    "description": "24-core EPYC 8224PN variant with reduced TDP and clocks, targeted at telco, edge, and carrier-grade deployments.",
    "series": "8004",
    "socket": "SP6",
    "cores": 24,
    "threads": 48,
    "base_freq": 2.0,
    "cache": 64,
    "tdp": 120,
    "tech": "5nm",
    "memory_type": "DDR5",
    "max_memory_size": 4800,
    "packaging": "Tray",
    "image": "/static/images/amd-epyc-series.jpeg",
    "price": 2450
  },


  {
    "id": "cpu-epyc-8124p",
    "name": "AMD EPYC 8124P",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "16-core EPYC 8124P with strong per-core performance and efficient 125W TDP, ideal for compact 1P servers and infrastructure services.",
    "series": "8004",
    "socket": "SP6",
    "cores": 16,
    "threads": 32,
    "base_freq": 2.45,
    "cache": 64,
    "tdp": 125,
    "tech": "5nm",
    "memory_type": "DDR5",
    "max_memory_size": 4800,
    "packaging": "Tray",
    "image": "/static/images/amd-epyc-series.jpeg",
    "price": 1900
  },

 
  {
    "id": "cpu-epyc-8124pn",
    "name": "AMD EPYC 8124PN",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server / Telco / Edge",
    "description": "16-core EPYC 8124PN low-power variant designed for space- and power-constrained edge and telco systems.",
    "series": "8004",
    "socket": "SP6",
    "cores": 16,
    "threads": 32,
    "base_freq": 2.1,
    "cache": 64,
    "tdp": 105,
    "tech": "5nm",
    "memory_type": "DDR5",
    "max_memory_size": 4800,
    "packaging": "Tray",
    "image": "/static/images/amd-epyc-series.jpeg",
    "price": 1800
  },


  {
    "id": "cpu-epyc-8024p",
    "name": "AMD EPYC 8024P",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "8-core entry EPYC 8024P processor built for low-core-count server roles, control plane services, and lightweight workloads.",
    "series": "8004",
    "socket": "SP6",
    "cores": 8,
    "threads": 16,
    "base_freq": 2.4,
    "cache": 32,
    "tdp": 90,
    "tech": "5nm",
    "memory_type": "DDR5",
    "max_memory_size": 4800,
    "packaging": "Tray",
    "image": "/static/images/amd-epyc-series.jpeg",
    "price": 1200
  },


  {
    "id": "cpu-epyc-8024pn",
    "name": "AMD EPYC 8024PN",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server / Telco / Edge",
    "description": "8-core EPYC 8024PN model tuned for ultra-low-power telco and edge deployments where energy efficiency and thermals are critical.",
    "series": "8004",
    "socket": "SP6",
    "cores": 8,
    "threads": 16,
    "base_freq": 2.0,
    "cache": 32,
    "tdp": 70,
    "tech": "5nm",
    "memory_type": "DDR5",
    "max_memory_size": 4800,
    "packaging": "Tray",
    "image": "/static/images/amd-epyc-series.jpeg",
    "price": 1150
  },
  {
"id":"cpu-epyc-4564p",
"name":"AMD EPYC 4564P",
"brand":"AMD","category":"AMD Server Processor","application":"Server",
"description":"High-frequency 16-core EPYC 4004 processor optimized for edge servers, virtualization, and business workloads.",
"series":"4004","socket":"AM5",
"cores":16,"threads":32,"base_freq":4.0,"cache":64,"tdp":170,
"tech":"5nm","memory_type":"DDR5","max_memory_size":256,
"packaging":"Tray","image":"/static/images/amd-epyc-series.jpeg","price":1750
},

{
"id":"cpu-epyc-4464p",
"name":"AMD EPYC 4464P",
"brand":"AMD","category":"AMD Server Processor","application":"Server",
"description":"Balanced 12-core EPYC CPU delivering strong per-core performance for SMB servers and virtualization.",
"series":"4004","socket":"AM5",
"cores":12,"threads":24,"base_freq":3.8,"cache":64,"tdp":160,
"tech":"5nm","memory_type":"DDR5","max_memory_size":256,
"packaging":"Tray","image":"/static/images/amd-epyc-series.jpeg","price":1350
},

{
"id":"cpu-epyc-4364p",
"name":"AMD EPYC 4364P",
"brand":"AMD","category":"AMD Server Processor","application":"Server",
"description":"8-core EPYC processor for entry-level servers, networking, and lightweight virtualization.",
"series":"4004","socket":"AM5",
"cores":8,"threads":16,"base_freq":3.7,"cache":64,"tdp":130,
"tech":"5nm","memory_type":"DDR5","max_memory_size":256,
"packaging":"Tray","image":"/static/images/amd-epyc-series.jpeg","price":980
},

{
"id":"cpu-epyc-4344p",
"name":"AMD EPYC 4344P",
"brand":"AMD","category":"AMD Server Processor","application":"Server",
"description":"Energy-efficient 8-core EPYC CPU for cloud edge, storage, and infrastructure services.",
"series":"4004","socket":"AM5",
"cores":8,"threads":16,"base_freq":3.5,"cache":32,"tdp":100,
"tech":"5nm","memory_type":"DDR5","max_memory_size":256,
"packaging":"Tray","image":"/static/images/amd-epyc-series.jpeg","price":890
},

{
"id":"cpu-epyc-4244p",
"name":"AMD EPYC 4244P",
"brand":"AMD","category":"AMD Server Processor","application":"Server",
"description":"6-core compact EPYC processor ideal for networking infrastructure and embedded compute.",
"series":"4004","socket":"AM5",
"cores":6,"threads":12,"base_freq":3.5,"cache":32,"tdp":85,
"tech":"5nm","memory_type":"DDR5","max_memory_size":256,
"packaging":"Tray","image":"/static/images/amd-epyc-series.jpeg","price":720
},

{
"id":"cpu-epyc-4124p",
"name":"AMD EPYC 4124P",
"brand":"AMD","category":"AMD Server Processor","application":"Server",
"description":"Entry-level 4-core EPYC processor optimized for low-power control servers and small-scale deployments.",
"series":"4004","socket":"AM5",
"cores":4,"threads":8,"base_freq":3.7,"cache":16,"tdp":65,
"tech":"5nm","memory_type":"DDR5","max_memory_size":256,
"packaging":"Tray","image":"/static/images/amd-epyc-series.jpeg","price":540
},

{
"id":"cpu-epyc-4584px",
"name":"AMD EPYC 4584PX",
"brand":"AMD","category":"AMD Server Processor","application":"Server",
"description":"High-performance 3D V-Cache enhanced EPYC processor for simulation, HPC, and analytics workloads.",
"series":"4004","socket":"AM5",
"cores":16,"threads":32,"base_freq":3.6,"cache":128,"tdp":190,
"tech":"5nm","memory_type":"DDR5","max_memory_size":256,
"packaging":"Tray","image":"/static/images/amd-epyc-series.jpeg","price":2200
},

{
"id":"cpu-epyc-4484px",
"name":"AMD EPYC 4484PX",
"brand":"AMD","category":"AMD Server Processor","application":"Server",
"description":"3D V-Cache powered EPYC CPU designed for low-latency, database, and compute-heavy enterprise workloads.",
"series":"4004","socket":"AM5",
"cores":12,"threads":24,"base_freq":3.6,"cache":128,"tdp":175,
"tech":"5nm","memory_type":"DDR5","max_memory_size":256,
"packaging":"Tray","image":"/static/images/amd-epyc-series.jpeg","price":1900
},

{
"id":"cpu-epyc-wof-4564p",
"name":"AMD EPYC WOF 4564P",
"brand":"AMD","category":"AMD Server Processor","application":"Server",
"description":"WOF edition 16-core EPYC CPU supplied without heatsink for system integrators.",
"series":"4004","socket":"AM5",
"cores":16,"threads":32,"base_freq":4.0,"cache":64,"tdp":170,
"tech":"5nm","memory_type":"DDR5","max_memory_size":256,
"packaging":"WOF","image":"/static/images/amd-epyc-series.jpeg","price":1680
},

{
"id":"cpu-epyc-wof-4464p",
"name":"AMD EPYC WOF 4464P",
"brand":"AMD","category":"AMD Server Processor","application":"Server",
"description":"12-core EPYC WOF processor for OEM deployments and custom rack builds.",
"series":"4004","socket":"AM5",
"cores":12,"threads":24,"base_freq":3.8,"cache":64,"tdp":160,
"tech":"5nm","memory_type":"DDR5","max_memory_size":256,
"packaging":"WOF","image":"/static/images/amd-epyc-series.jpeg","price":1280
},

{
"id":"cpu-epyc-wof-4364p",
"name":"AMD EPYC WOF 4364P",
"brand":"AMD","category":"AMD Server Processor","application":"Server",
"description":"8-core EPYC WOF processor for embedded, networking, and appliance systems.",
"series":"4004","socket":"AM5",
"cores":8,"threads":16,"base_freq":3.7,"cache":64,"tdp":130,
"tech":"5nm","memory_type":"DDR5","max_memory_size":256,
"packaging":"WOF","image":"/static/images/amd-epyc-series.jpeg","price":940
},

{
"id":"cpu-epyc-wof-4344p",
"name":"AMD EPYC WOF 4344P",
"brand":"AMD","category":"AMD Server Processor","application":"Server",
"description":"Energy-efficient WOF EPYC CPU for telco, firewall, and microserver roles.",
"series":"4004","socket":"AM5",
"cores":8,"threads":16,"base_freq":3.5,"cache":32,"tdp":100,
"tech":"5nm","memory_type":"DDR5","max_memory_size":256,
"packaging":"WOF","image":"/static/images/amd-epyc-series.jpeg","price":850
},

{
"id":"cpu-epyc-wof-4244p",
"name":"AMD EPYC WOF 4244P",
"brand":"AMD","category":"AMD Server Processor","application":"Server",
"description":"6-core EPYC WOF CPU built for entry-level networking and router compute.",
"series":"4004","socket":"AM5",
"cores":6,"threads":12,"base_freq":3.5,"cache":32,"tdp":85,
"tech":"5nm","memory_type":"DDR5","max_memory_size":256,
"packaging":"WOF","image":"/static/images/amd-epyc-series.jpeg","price":690
},

{
"id":"cpu-epyc-wof-4124p",
"name":"AMD EPYC WOF 4124P",
"brand":"AMD","category":"AMD Server Processor","application":"Server",
"description":"Low-power quad-core EPYC processor for embedded compute and control-plane servers.",
"series":"4004","socket":"AM5",
"cores":4,"threads":8,"base_freq":3.7,"cache":16,"tdp":65,
"tech":"5nm","memory_type":"DDR5","max_memory_size":256,
"packaging":"WOF","image":"/static/images/amd-epyc-series.jpeg","price":510
},

{
"id":"cpu-epyc-wof-4484px",
"name":"AMD EPYC WOF 4484PX",
"brand":"AMD","category":"AMD Server Processor","application":"Server",
"description":"3D V-Cache enhanced WOF EPYC processor for HPC and low-latency compute environments.",
"series":"4004","socket":"AM5",
"cores":12,"threads":24,"base_freq":3.6,"cache":128,"tdp":175,
"tech":"5nm","memory_type":"DDR5","max_memory_size":256,
"packaging":"WOF","image":"/static/images/amd-epyc-series.jpeg","price":1850
},

{
"id":"cpu-epyc-wof-4584px",
"name":"AMD EPYC WOF 4584PX",
"brand":"AMD","category":"AMD Server Processor","application":"Server",
"description":"Highest-tier WOF EPYC 4004 CPU for compute-heavy simulation, analytics, and AI inference.",
"series":"4004","socket":"AM5",
"cores":16,"threads":32,"base_freq":3.6,"cache":128,"tdp":190,
"tech":"5nm","memory_type":"DDR5","max_memory_size":256,
"packaging":"WOF","image":"/static/images/amd-epyc-series.jpeg","price":2150
},

#4005

{
    "id": "cpu-epyc-4565p",
    "name": "AMD EPYC 4565P",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "16-core AMD EPYC 4565P built on Zen 5, delivering high clock speeds and strong efficiency for compact single-socket servers and virtualization.",
    "series": "4005",
    "socket": "AM5",
    "cores": 16,
    "threads": 32,
    "base_freq": 4.3,          
    "cache": 64,               
    "tdp": 170,                
    "tech": "4nm (Zen 5)",
    "memory_type": "DDR5",
    "max_memory_size": 256,    
    "packaging": "Tray",
    "image": "/static/images/amd-epyc-series.jpeg",
    "price": 589               
  },

  {
    "id": "cpu-epyc-4545p",
    "name": "AMD EPYC 4545P",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "16-core low-power EPYC 4545P tuned for high efficiency with a 65W TDP, ideal for energy-conscious dedicated servers and edge deployments.",
    "series": "4005",
    "socket": "AM5",
    "cores": 16,
    "threads": 32,
    "base_freq": 3.0,       
    "cache": 64,              
    "tdp": 65,                 
    "tech": "4nm (Zen 5)",
    "memory_type": "DDR5",
    "max_memory_size": 256,
    "packaging": "Tray",
    "image": "/static/images/amd-epyc-series.jpeg",
    "price": 550            
  },

  {
    "id": "cpu-epyc-4465p",
    "name": "AMD EPYC 4465P",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "12-core EPYC 4465P offering strong per-core performance at 65W, great for mid-range virtualized and application servers.",
    "series": "4005",
    "socket": "AM5",
    "cores": 12,
    "threads": 24,
    "base_freq": 3.4,          
    "cache": 64,               
    "tdp": 65,                 
    "tech": "4nm (Zen 5)",
    "memory_type": "DDR5",
    "max_memory_size": 256,
    "packaging": "Tray",
    "image": "/static/images/amd-epyc-series.jpeg",
    "price": 449               
  },

  {
    "id": "cpu-epyc-4345p",
    "name": "AMD EPYC 4345P",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "8-core AMD EPYC 4345P with high base clocks and 65W TDP, ideal for network appliances, control-plane, and light virtualization.",
    "series": "4005",
    "socket": "AM5",
    "cores": 8,
    "threads": 16,
    "base_freq": 3.8,          
    "cache": 32,              
    "tdp": 65,                
    "tech": "4nm (Zen 5)",
    "memory_type": "DDR5",
    "max_memory_size": 256,
    "packaging": "Tray",
    "image": "/static/images/amd-epyc-series.jpeg",
    "price": 329               
  },

  {
    "id": "cpu-epyc-4245p",
    "name": "AMD EPYC 4245P",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "6-core EPYC 4245P designed for entry-level servers, microservices, and edge computing with low power draw.",
    "series": "4005",
    "socket": "AM5",
    "cores": 6,
    "threads": 12,
    "base_freq": 3.9,          
    "cache": 32,               
    "tdp": 65,                
    "tech": "4nm (Zen 5)",
    "memory_type": "DDR5",
    "max_memory_size": 256,
    "packaging": "Tray",
    "image": "/static/images/amd-epyc-series.jpeg",
    "price": 279               
  },

  {
    "id": "cpu-epyc-4585px",
    "name": "AMD EPYC 4585PX",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server / HPC",
    "description": "16-core EPYC 4585PX with 128 MB 3D V-Cache and very high boost clocks, targeting memory-sensitive, low-latency, and HPC-style workloads.",
    "series": "4005",
    "socket": "AM5",
    "cores": 16,
    "threads": 32,
    "base_freq": 4.3,         
    "cache": 128,              
    "tdp": 170,               
    "tech": "4nm (Zen 5)",
    "memory_type": "DDR5",
    "max_memory_size": 256,
    "packaging": "Tray",
    "image": "/static/images/amd-epyc-series.jpeg",
    "price": 699               
  },

 
  {
    "id": "cpu-epyc-wof-4565p",
    "name": "AMD EPYC WOF 4565P",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "16-core EPYC 4565P WOF (without fan/HSF), ideal for OEM and integrator server platforms using custom cooling.",
    "series": "4005",
    "socket": "AM5",
    "cores": 16,
    "threads": 32,
    "base_freq": 4.3,
    "cache": 64,
    "tdp": 170,
    "tech": "4nm (Zen 5)",
    "memory_type": "DDR5",
    "max_memory_size": 256,
    "packaging": "WOF",
    "image": "/static/images/amd-epyc-series.jpeg",
    "price": 569             
  },

  {
    "id": "cpu-epyc-wof-4545p",
    "name": "AMD EPYC WOF 4545P",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "EPYC 4545P WOF model for dense, efficient single-socket systems where integrators provide their own cooling solution.",
    "series": "4005",
    "socket": "AM5",
    "cores": 16,
    "threads": 32,
    "base_freq": 3.0,
    "cache": 64,
    "tdp": 65,
    "tech": "4nm (Zen 5)",
    "memory_type": "DDR5",
    "max_memory_size": 256,
    "packaging": "WOF",
    "image": "/static/images/amd-epyc-series.jpeg",
    "price": 530
  },

  {
    "id": "cpu-epyc-wof-4465p",
    "name": "AMD EPYC WOF 4465P",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server",
    "description": "12-core EPYC 4465P WOF edition built for OEM and appliance-style systems with custom thermal designs.",
    "series": "4005",
    "socket": "AM5",
    "cores": 12,
    "threads": 24,
    "base_freq": 3.4,
    "cache": 64,
    "tdp": 65,
    "tech": "4nm (Zen 5)",
    "memory_type": "DDR5",
    "max_memory_size": 256,
    "packaging": "WOF",
    "image": "/static/images/amd-epyc-series.jpeg",
    "price": 430
  },

  {
    "id": "cpu-epyc-wof-4345p",
    "name": "AMD EPYC WOF 4345P",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server / Network",
    "description": "8-core EPYC 4345P WOF SKU for compact network security, firewall, and edge appliances.",
    "series": "4005",
    "socket": "AM5",
    "cores": 8,
    "threads": 16,
    "base_freq": 3.8,
    "cache": 32,
    "tdp": 65,
    "tech": "4nm (Zen 5)",
    "memory_type": "DDR5",
    "max_memory_size": 256,
    "packaging": "WOF",
    "image": "/static/images/amd-epyc-series.jpeg",
    "price": 315
  },

  {
    "id": "cpu-epyc-wof-4245p",
    "name": "AMD EPYC WOF 4245P",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server / Embedded",
    "description": "6-core EPYC 4245P WOF optimized for embedded servers, industrial controllers, and low-power networking gear.",
    "series": "4005",
    "socket": "AM5",
    "cores": 6,
    "threads": 12,
    "base_freq": 3.9,
    "cache": 32,
    "tdp": 65,
    "tech": "4nm (Zen 5)",
    "memory_type": "DDR5",
    "max_memory_size": 256,
    "packaging": "WOF",
    "image": "/static/images/amd-epyc-series.jpeg",
    "price": 265
  },

  {
    "id": "cpu-epyc-wof-4585px",
    "name": "AMD EPYC WOF 4585PX",
    "brand": "AMD",
    "category": "AMD Server Processor",
    "application": "Server / HPC",
    "description": "WOF version of the EPYC 4585PX with 16 cores and 128 MB 3D V-Cache, ideal for custom-cooled HPC and simulation servers.",
    "series": "4005",
    "socket": "AM5",
    "cores": 16,
    "threads": 32,
    "base_freq": 4.3,
    "cache": 128,
    "tdp": 170,
    "tech": "4nm (Zen 5)",
    "memory_type": "DDR5",
    "max_memory_size": 256,
    "packaging": "WOF",
    "image": "/static/images/amd-epyc-series.jpeg",
    "price": 679
  }
  
]



