memory_products = [

#  SAMSUMG MEMORY

{
  "id": "ram-samsung-8gb-ddr4-udimm",
  "name": "Samsung 8GB DDR4 UDIMM",
  "brand": "Samsung",
  "category": "Desktop Memory Module",
  "category_key": "memory",
  "sub_category": "samsung",
  "application": "Desktop PC",
  "description": "8 GB DDR4 unbuffered DIMM module for desktop computers — 288-pin, 1.2 V, non-ECC, UDIMM.",
  "capacity": "8GB",
  "series": "samsung-ram",
  "memory_type": "DDR4 SDRAM",
  "speed": "2400 MHz (PC4-19200)",
  "voltage": "1.2V",
  "series":"samsung-ram",
  "pins": 288,
  "form_factor": "UDIMM (DIMM)",
  "ecc": "false",
  "registered": "false",
  "model": "M378A1K43CB2-CRC",
  "image": "/static/images/samsung_memory.jpg",
  "price": 6840.00
},

{
  "id": "ram-samsung-16gb-ddr4-udimm",
  "name": "Samsung 16GB DDR4 UDIMM",
  "brand": "Samsung",
              "category_key": "memory",
    "sub_category": "samsung",
  "category": "Desktop Memory Module",
  "application": "Desktop PC",
  "description": "16 GB DDR4 unbuffered DIMM module for desktop computers — 288-pin, 1.2 V, non-ECC, UDIMM.",
  "capacity": "16GB",
  "series": "ddr4",
  "memory_type": "DDR4 SDRAM",
  "speed": "2400 MHz (PC4-19200)",  
  "voltage": "1.2V",
  "pins": 288,
  "form_factor": "UDIMM (DIMM)",
  "ecc": "false",
  "registered": "false",
  "model": "M378A2K43CB1-CRC",
  "image": "/static/images/samsung_memory.jpg",
  "price": 11428.00
},

{
  "id": "ram-samsung-32gb-ddr4-udimm",
  "name": "Samsung 32GB DDR4 UDIMM",
  "brand": "Samsung",
  "category": "Desktop Memory Module",
              "category_key": "memory",
    "sub_category": "samsung",
  "application": "Desktop PC",
  "description": "32 GB DDR4 unbuffered DIMM module for desktop computers — 288-pin, 1.2 V, non-ECC, UDIMM.",
  "capacity": "32GB",
  "series": "samsung-ram",
  "memory_type": "DDR4 SDRAM",
  "speed": "3200 MHz (PC4-25600)",  
  "voltage": "1.2V",
  "pins": 288,
  "form_factor": "UDIMM (DIMM)",
  "ecc": "false",
  "registered": "false",
  "model": "M378A4G43AB2-CWE",
  "image": "/static/images/samsung_memory.jpg",
  "price": 15599.00
},

{
  "id": "ram-samsung-16gb-ddr5-udimm",
  "name": "Samsung 16GB DDR5 UDIMM",
  "brand": "Samsung",
              "category_key": "memory",
    "sub_category": "samsung",
  "category": "Desktop Memory Module",
  "application": "Desktop PC",
  "description": "16 GB DDR5 unbuffered DIMM module for desktop computers — 288-pin, 1.1 V (JEDEC standard), non-ECC, UDIMM.",
  "capacity": "16GB",
  "series": "samsung-ram",
  "memory_type": "DDR5 SDRAM",
  "speed": "5600 MHz (PC5-44800)",  
  "voltage": "1.1V",
  "pins": 288,
  "form_factor": "UDIMM (DIMM)",
  "ecc": "false",
  "registered": "false",
  "model": "M323R2GA3DB0-CWM",
  "image": "/static/images/samsung_memory.jpg",
  "price": 21003.00
},

{
  "id": "ram-samsung-32gb-ddr5-udimm",
  "name": "Samsung 32GB DDR5 UDIMM",
  "brand": "Samsung",
  "category": "Desktop Memory Module",
              "category_key": "memory",
    "sub_category": "samsung",
  "application": "Desktop PC",
  "description": "32 GB DDR5 unbuffered DIMM module for desktop computers — 288-pin, 1.1 V, non-ECC, UDIMM.",
  "capacity": "32GB",
  "series": "samsung-ram",
  "memory_type": "DDR5 SDRAM",
  "speed": "5600 MHz (PC5-44800)",
  "voltage": "1.1V",
  "pins": 288,
  "form_factor": "UDIMM (DIMM)",
  "ecc": "false",
  "registered": "false",
  "model": "M323R4GA3DB0-CWM",
  "image": "/static/images/samsung_memory.jpg",
  "price": 43271.00
},

{
  "id": "ram-samsung-32gb-ddr4-rdimm",
  "name": "Samsung 32GB DDR4 RDIMM",
  "brand": "Samsung",
  "category": "Server Memory Module",
  "application": "Server",
  "description": "32 GB DDR4 registered DIMM module for servers — 288-pin, 1.2 V, ECC, RDIMM.",
  "capacity": "32GB",
              "category_key": "memory",
    "sub_category": "samsung",
  "series": "samsung-ram",
  "memory_type": "DDR4 SDRAM",
  "speed": "2400 MHz (PC4-19200)",  
  "voltage": "1.2V",
  "pins": 288,
  "form_factor": "RDIMM (DIMM)",
  "ecc": "true",
  "registered": "true",
  "model": "M393A4K40BB1-CRC",
  "image": "/static/images/samsung_memory.jpg",
  "price": 15632.59
},

{
  "id": "ram-samsung-64gb-ddr4-lrdimm",
  "name": "Samsung 64GB DDR4 LRDIMM",
  "brand": "Samsung",
              "category_key": "memory",
    "sub_category": "samsung",
  "category": "Server Memory Module",
  "application": "Server",
  "description": "64 GB DDR4 load-reduced DIMM module for servers — 288-pin, 1.2 V, ECC, LRDIMM.",
  "capacity": "64GB",
  "series": "samsung-ram",
  "memory_type": "DDR4 SDRAM",
  "speed": "2666 MHz (PC4-21300V-L)",  
  "voltage": "1.2V",
  "pins": 288,
  "form_factor": "LRDIMM (DIMM)",
  "ecc": "true",
  "registered": "false",
  "model": "M386A8K40BM2-CTD",
  "image": "/static/images/samsung_memory.jpg",
  "price": 530.00
},


#  CRUCIAL MEMORY


{
  "id": "ram-crucial-8gb-ddr4-udimm",
  "name": "Crucial 8GB DDR4 UDIMM",
  "brand": "Crucial",
              "category_key": "memory",
  "category": "Desktop Memory Module",
  "application": "Desktop PC",
  "description": "8 GB DDR4 unbuffered DIMM module for desktop computers — 288-pin, 1.2 V, non-ECC, UDIMM.",
  "capacity": "8GB",
  "series": "crucial-ram",
  "memory_type": "DDR4 SDRAM",
  "speed": "3200 MHz (PC4-25600)",
  "voltage": "1.2V",
  "pins": 288,
  "form_factor": "UDIMM (DIMM)",
  "ecc": "false",
  "registered": "false",
  "model": "CB8GU3200",
  "image": "/static/images/crucial_memory.jpg",
  "price": 4999.00
},

{
  "id": "ram-crucial-16gb-ddr4-udimm",
  "name": "Crucial 16GB DDR4 UDIMM",
  "brand": "Crucial",
  "category": "Desktop Memory Module",
  "application": "Desktop PC",
                "category_key": "memory",
    "sub_category": "crucial",
  "description": "16 GB DDR4 unbuffered DIMM module for desktop computers — 288-pin, 1.2 V, non-ECC, UDIMM.",
  "capacity": "16GB",
  "series": "crucial-ram",
  "memory_type": "DDR4 SDRAM",
  "speed": "3200 MHz (PC4-25600)",
  "voltage": "1.2V",
  "pins": 288,
  "form_factor": "UDIMM (DIMM)",
  "ecc": "false",
  "registered": "false",
  "model": "CT16G4DFRA32A",
  "image": "/static/images/crucial_memory.jpg",
  "price": 12400.00
},

{
  "id": "ram-crucial-8gb-ddr4-sodimm",
  "name": "Crucial 8GB DDR4 SODIMM",
  "brand": "Crucial",
                "category_key": "memory",
    "sub_category": "crucial",
  "category": "Laptop Memory Module",
  "application": "Laptop PC",
  "description": "8 GB DDR4 unbuffered SO-DIMM module for laptops — 260-pin, 1.2 V, non-ECC, SODIMM.",
  "capacity": "8GB",
  "series": "crucial-ram",
  "memory_type": "DDR4 SDRAM",
  "speed": "2400 MHz (PC4-19200)",
  "voltage": "1.2V",
  "pins": 260,
  "form_factor": "SODIMM (Laptop DIMM)",
  "ecc": "false",
  "registered": "false",
  "model": "CT8G4SFS824A",
  "image": "/static/images/crucial_memory.jpg",
  "price": 5082.00
},

{
  "id": "ram-crucial-32gb-ddr4-rdimm",
  "name": "Crucial 32GB DDR4 RDIMM",
  "brand": "Crucial",
  "category": "Server Memory Module",
  "application": "Server",
  "description": "32 GB DDR4 registered DIMM module for servers — 288-pin, 1.2 V, ECC, RDIMM.",
  "capacity": "32GB",
  "series": "crucial-ram",
                "category_key": "memory",
    "sub_category": "crucial",
  "memory_type": "DDR4 SDRAM",
  "speed": "2666 MHz (PC4-21300)",
  "voltage": "1.2V",
  "pins": 288,
  "form_factor": "RDIMM (DIMM)",
  "ecc": "true",
  "registered": "true",
  "model": "CT32G4RFD4266",
  "image": "/static/images/crucial_memory.jpg",
  "price": 18045.00
},

{
  "id": "ram-crucial-64gb-ddr4-lrdimm",
  "name": "Crucial 64GB DDR4 LRDIMM",
  "brand": "Crucial",
                "category_key": "memory",
    "sub_category": "crucial",
  "category": "Server Memory Module",
  "application": "Server / Workstation",
  "description": "64 GB DDR4 load-reduced registered DIMM module for servers — 288-pin, 1.2 V, ECC, LRDIMM.",
  "capacity": "64GB",
  "series": "crucial-ram",
  "memory_type": "DDR4 SDRAM",
  "speed": "3200 MHz (PC4-25600)",
  "voltage": "1.2V",
  "pins": 288,
  "form_factor": "LRDIMM (DIMM)",
  "ecc": "true",
  "registered": "true",
  "model": "MTA36ASF8G72LZ-3G2R",  
  "image": "/static/images/crucial_memory.jpg",
  "price": 67953.00
},



#  MICRON MEMORY


{
  "id": "ram-micron-8gb-ddr4-udimm",
  "name": "Micron 8GB DDR4 UDIMM",
  "brand": "Micron",
                "category_key": "memory",
    "sub_category": "micron",
  "category": "Desktop Memory Module",
  "application": "Desktop PC",
  "description": "8 GB DDR4 unbuffered DIMM module for desktop computers — 288-pin, 1.2 V, non-ECC, UDIMM.",
  "capacity": "8GB",
  "series": "micron-ram",
  "memory_type": "DDR4 SDRAM",
  "speed": "2666 MHz (PC4-21300)",
  "voltage": "1.2V",
  "pins": 288,
  "form_factor": "UDIMM (DIMM)",
  "ecc": "false",
  "registered": "false",
  "model": "MTA8ATF1G64AZ-2G6E1",
  "image": "/static/images/micron_memory.jpg",
  "price": 7189.00
},

{
  "id": "ram-micron-16gb-ddr4-udimm",
  "name": "Micron 16GB DDR4 UDIMM",
  "brand": "Micron",
  "category": "Desktop Memory Module",
  "application": "Desktop PC",
  "description": "16 GB DDR4 unbuffered DIMM module for desktop computers — 288-pin, 1.2 V, non-ECC, UDIMM.",
  "capacity": "16GB",
  "series": "micron-ram",
                  "category_key": "memory",
    "sub_category": "micron",
  "memory_type": "DDR4 SDRAM",
  "speed": "3200 MHz (PC4-25600)",
  "voltage": "1.2V",
  "pins": 288,
  "form_factor": "UDIMM (DIMM)",
  "ecc": "false",
  "registered": "false",
  "model": "MTA8ATF2G64AZ-3G2F1",
  "image": "/static/images/micron_memory.jpg",
  "price": 19727.00
},

{
  "id": "ram-micron-32gb-ddr4-rdimm",
  "name": "Micron 32GB DDR4 RDIMM",
  "brand": "Micron",
  "category": "Server Memory Module",
  "application": "Server",
  "description": "32 GB DDR4 registered DIMM module for servers — 288-pin, 1.2 V, ECC, RDIMM.",
  "capacity": "32GB",
                  "category_key": "memory",
    "sub_category": "micron",
  "series": "micron-ram",
  "memory_type": "DDR4 SDRAM",
  "speed": "3200 MHz (PC4-25600R)",
  "voltage": "1.2V",
  "pins": 288,
  "form_factor": "RDIMM (DIMM)",
  "ecc": "true",
  "registered": "true",
  "model": "MTA36ASF4G72PZ-3G2",
  "image": "/static/images/micron_memory.jpg",
  "price": 18000.00
},

{
  "id": "ram-micron-64gb-ddr4-lrdimm",
  "name": "Micron 64GB DDR4 LRDIMM",
  "brand": "Micron",
  "category": "Server Memory Module",
  "application": "Server / Workstation",
  "description": "64 GB DDR4 load-reduced registered DIMM module for servers — 288-pin, 1.2 V, ECC, LRDIMM.",
  "capacity": "64GB",
  "series": "micron-ram",
                  "category_key": "memory",
    "sub_category": "micron",
  "memory_type": "DDR4 SDRAM",
  "speed": "3200 MHz (PC4-25600R)",  
  "voltage": "1.2V",
  "pins": 288,
  "form_factor": "LRDIMM (DIMM)",
  "ecc": "true",
  "registered": "true",
  "model": "MTA36ASF8G72LZ-3G2F1",
  "image": "/static/images/micron_memory.jpg",
  "price": 67953.00
}


]
