ssd_products = [

#  SAMSUNG SSD   

{
  "id": "ssd-870evo-250gb",
  "name": "Samsung 870 EVO 250GB",
  "brand": "Samsung",
  "category": "Internal SSD",
  "application": "Storage",
  "description": "Samsung 870 EVO 250GB is a high-performance SATA SSD designed for desktops and laptops, offering fast read/write speeds of up to 560/530 MB/s. Built with Samsung V-NAND and a 512MB DRAM cache, it improves system boot time, application loading, and overall responsiveness. Ideal for OS installation and storage upgrades with excellent endurance and reliability.",
  "series": "870-evo",
  "socket": "SATA III (6Gb/s)",
  "capacity": "250GB",
  "cache": "512MB LPDDR4",
  "read_speed": "Up to 560 MB/s",
  "write_speed": "Up to 530 MB/s",
  "tech": "Samsung V-NAND 3-bit MLC",
  "memory_type": "V-NAND",
  "max_memory_size": "250GB",
  "tdp": "Low-power (SSD – no TDP rating)",
  "packaging": "Boxed (Drive + Documentation)",
  "image": "/static/images/SSD.webp",
  "price": 39.00
},

{
  "id": "ssd-870evo-500gb",
  "name": "Samsung 870 EVO 500GB",
  "brand": "Samsung",
  "category": "Internal SSD",
  "application": "Storage",
  "description": "Samsung 870 EVO 500GB is a fast and reliable SATA SSD equipped with Samsung V-NAND technology and 512MB DRAM cache for enhanced performance. With sequential read/write speeds reaching 560/530 MB/s, it's ideal for operating system installation, application performance, storage upgrades, and improving laptop/desktop speed. Known for durability, stability, and long-term reliability.",
  "series": "870-evo",
  "socket": "SATA III (6Gb/s)",
  "capacity": "500GB",
  "cache": "512MB LPDDR4",
  "read_speed": "Up to 560 MB/s",
  "write_speed": "Up to 530 MB/s",
  "tech": "Samsung V-NAND 3-bit MLC",
  "memory_type": "V-NAND",
  "max_memory_size": "500GB",
  "tdp": "Low-power (SSD – no standard TDP rating)",
  "packaging": "Boxed (SSD + Documentation)",
  "image": "/static/images/SSD.webp",
  "price": 59.00,
},

{
  "id": "ssd-870evo-1tb",
  "name": "Samsung 870 EVO 1TB",
  "brand": "Samsung",
  "category": "Internal SSD",
  "application": "Storage",
  "description": "Samsung 870 EVO 1TB is a high-quality SATA SSD built with Samsung V-NAND and a 1GB DRAM cache, offering fast and reliable performance for desktops and laptops. With sequential speeds up to 560/530 MB/s, it significantly improves system responsiveness, boot time, loading speed, and file transfers. Known for durability and long endurance, making it ideal for OS drives, gaming storage, and professional workloads.",
  "series": "870-evo",
  "socket": "SATA III (6Gb/s)",
  "capacity": "1TB",
  "cache": "1GB LPDDR4",
  "read_speed": "Up to 560 MB/s",
  "write_speed": "Up to 530 MB/s",
  "tech": "Samsung V-NAND 3-bit MLC",
  "memory_type": "V-NAND",
  "max_memory_size": "1TB",
  "tdp": "Low-power SSD (no standard TDP value)",
  "packaging": "Boxed (SSD + Documentation)",
  "image": "/static/images/SSD.webp",
  "price": 89.00
},

{
  "id": "ssd-870evo-2tb",
  "name": "Samsung 870 EVO 2TB",
  "brand": "Samsung",
  "category": "Internal SSD",
  "application": "Storage",
  "description": "Samsung 870 EVO 2TB is a premium SATA SSD powered by Samsung V-NAND and enhanced controller, offering fast read/write speeds of up to 560/530 MB/s. With a 2GB DRAM cache, it provides superior responsiveness, fast boot time, rapid application loading, and reliable long-term performance. Perfect for large storage needs such as gaming libraries, media editing, OS installation, and workstation workloads.",
  "series": "870-evo",
  "socket": "SATA III (6Gb/s)",
  "capacity": "2TB",
  "cache": "2GB LPDDR4",
  "read_speed": "Up to 560 MB/s",
  "write_speed": "Up to 530 MB/s",
  "tech": "Samsung V-NAND 3-bit MLC",
  "memory_type": "V-NAND",
  "max_memory_size": "2TB",
  "tdp": "Low power SSD (no fixed TDP rating)",
  "packaging": "Boxed (SSD + Documentation)",
  "image": "/static/images/SSD.webp",
  "price": 169.00
},

{
  "id": "ssd-870qvo-1tb",
  "name": "Samsung 870 QVO 1TB",
  "brand": "Samsung",
  "category": "Internal SSD",
  "application": "Storage",
  "description": "Samsung 870 QVO 1TB is a high-capacity SATA SSD designed with QLC V-NAND technology for cost-effective mass storage. With sequential speeds up to 560/530 MB/s and a 1GB DRAM cache, it delivers quick application loading, reliable performance, and efficient storage for everyday computing. Perfect for large data storage, gaming libraries, backups, and general use at an affordable price range.",
  "series": "870-evo",
  "socket": "SATA III (6Gb/s)",
  "capacity": "1TB",
  "cache": "1GB LPDDR4",
  "read_speed": "Up to 560 MB/s",
  "write_speed": "Up to 530 MB/s",
  "tech": "Samsung QLC V-NAND",
  "memory_type": "QLC NAND",
  "max_memory_size": "1TB",
  "tdp": "Low-power SSD (no fixed TDP specification)",
  "packaging": "Boxed (SSD + Documentation)",
  "image": "/static/images/SSD.webp",
  "price": 79.00
},

{
  "id": "ssd-980-250gb",
  "name": "Samsung 980 250GB",
  "brand": "Samsung",
  "category": "Internal NVMe SSD",
  "application": "Storage",
  "description": "Samsung 980 250GB is an entry-level NVMe PCIe 3.0 SSD featuring Samsung V-NAND technology and HMB for improved performance without onboard DRAM. With read speeds up to 2900 MB/s and write speeds up to 1300 MB/s, it offers a major speed boost over SATA SSDs. Ideal for OS installation, fast boot times, application performance, and lightweight gaming builds.",
  "series": "980-pro",
  "socket": "M.2 NVMe (PCIe 3.0 x4)",
  "capacity": "250GB",
  "cache": "HMB Technology (No DRAM onboard)",
  "read_speed": "Up to 2900 MB/s",
  "write_speed": "Up to 1300 MB/s",
  "tech": "Samsung V-NAND",
  "memory_type": "V-NAND",
  "max_memory_size": "250GB",
  "tdp": "Low-power SSD (varies with load)",
  "packaging": "Boxed (M.2 SSD + Documentation)",
  "image": "/static/images/SSD.webp",
  "price": 39.00
},

{
  "id": "ssd-980pro-1tb",
  "name": "Samsung 980 PRO 1TB",
  "brand": "Samsung",
  "category": "Internal NVMe SSD",
  "application": "Storage",
  "description": "Samsung 980 PRO 1TB is a high-performance PCIe 4.0 NVMe SSD designed for gaming PCs, workstations, and high-speed data processing. With blazing read/write speeds up to 7000/5000 MB/s and onboard DRAM cache, it delivers exceptional performance for heavy workloads, 4K editing, rendering, and next-gen gaming. Ideal for high-end builds requiring fast load times, rapid boot speeds, and reliable sustained performance.",
  "series": "980-pro",
  "socket": "M.2 NVMe (PCIe 4.0 x4)",
  "capacity": "1TB",
  "cache": "1GB LPDDR4 DRAM",
  "read_speed": "Up to 7000 MB/s",
  "write_speed": "Up to 5000 MB/s",
  "tech": "Samsung V-NAND 3-bit MLC",
  "memory_type": "V-NAND",
  "max_memory_size": "1TB",
  "tdp": "Low-power SSD (varies under heavy load)",
  "packaging": "Boxed (M.2 SSD + Documentation)",
  "image": "/static/images/SSD.webp",
  "price": 119.00
},

{
  "id": "ssd-990pro-1tb",
  "name": "Samsung 990 PRO 1TB",
  "brand": "Samsung",
  "category": "Internal NVMe SSD",
  "application": "Storage",
  "description": "Samsung 990 PRO 1TB is a next-generation PCIe 4.0 NVMe SSD offering extremely fast speeds for gaming, content creation, and high-performance workloads. With read/write speeds up to 7450/6900 MB/s and 1GB DRAM cache, it delivers exceptional responsiveness for 4K/8K editing, rendering, large file transfers, and high-end desktop builds. Designed for enthusiasts demanding maximum performance with improved power efficiency and durable V-NAND technology.",
  "series": "990-pro",
  "socket": "M.2 NVMe (PCIe 4.0 x4)",
  "capacity": "1TB",
  "cache": "1GB LPDDR4 DRAM",
  "read_speed": "Up to 7450 MB/s",
  "write_speed": "Up to 6900 MB/s",
  "tech": "Samsung 7th-Gen V-NAND",
  "memory_type": "V-NAND",
  "max_memory_size": "1TB",
  "tdp": "Low-power SSD (varies during load)",
  "packaging": "Boxed (M.2 SSD + Manual)",
  "image": "/static/images/SSD.webp",
  "price": 149.00
},


{
  "id": "ssd-pm9a3-enterprise-1.92tb",
  "name": "Samsung PM9A3 Enterprise NVMe SSD",
  "brand": "Samsung",
  "category": "Enterprise NVMe SSD",
  "application": "Server / Datacenter Storage",
  "description": "Samsung PM9A3 is an enterprise-class PCIe 4.0 NVMe SSD designed for data centers and heavy server workloads. It offers extremely high efficiency, durability, and sustained performance for 24/7 read-intensive environments. With speeds up to 6.5GB/s and DRAM caching, it delivers exceptional reliability for virtualization, cloud storage, high IOPS workloads, and database applications. Available in U.2/M.2/E1.S form factors supporting scale-out server infrastructure.",
  "series": "pm9a3",
  "socket": "U.2 / M.2 / E1.S (varies by model)",
  "capacity": "1.92TB",
  "cache": "DRAM Cache Enabled",
  "read_speed": "Up to 6,500 MB/s",
  "write_speed": "Up to 3,500 MB/s",
  "tech": "V-NAND TLC (PCIe 4.0 x4)",
  "memory_type": "Enterprise V-NAND",
  "max_memory_size": "1.92TB",
  "tdp": "Highly Efficient (Power optimized for server use)",
  "packaging": "OEM/Tray (Enterprise Packaging)",
  "image": "/static/images/samsung_pm9a3_enterprise.jpg",
  "price": 299.00
},


#  CRUCIAL SSD

{
  "id": "ssd-mx500-500gb",
  "name": "Crucial MX500 500GB",
  "brand": "Crucial",
  "category": "Internal SSD",
  "application": "Storage",
  "description": "Crucial MX500 500GB is a reliable SATA SSD built with Micron 3D NAND technology, delivering excellent performance and durability. With read/write speeds up to 560/510 MB/s and a 512MB DRAM cache, it ensures fast boot times, quick application loading, and responsive system performance. Known for strong endurance, power efficiency, and integrated AES 256-bit hardware encryption, making it ideal for desktops and laptop upgrades.",
  "series": "mx500",
  "socket": "SATA III (6Gb/s)",
  "capacity": "500GB",
  "cache": "512MB LPDDR3 DRAM",
  "read_speed": "Up to 560 MB/s",
  "write_speed": "Up to 510 MB/s",
  "tech": "Micron 3D NAND",
  "memory_type": "3D NAND",
  "max_memory_size": "500GB",
  "tdp": "Low-power SSD (minimal consumption)",
  "packaging": "Boxed (SSD + Manual/Installation Guide)",
  "image": "/static/images/SSD.webp",
  "price": 49.00
},

{
  "id": "ssd-p3-500gb",
  "name": "Crucial P3 500GB",
  "brand": "Crucial",
  "category": "Internal NVMe SSD",
  "application": "Storage",
  "description": "Crucial P3 500GB is a value-focused NVMe PCIe 3.0 SSD that offers fast performance for everyday tasks, OS installation, and gaming loads. Powered by Micron 3D NAND and HMB technology, it reaches speeds up to 3500/1900 MB/s, making it much faster than SATA SSDs. Ideal for users looking to upgrade storage speed affordably, suitable for laptops and desktops.",
  "series": "p3",
  "socket": "M.2 NVMe (PCIe 3.0 x4)",
  "capacity": "500GB",
  "cache": "HMB Technology (No onboard DRAM)",
  "read_speed": "Up to 3500 MB/s",
  "write_speed": "Up to 1900 MB/s",
  "tech": "Micron 3D NAND",
  "memory_type": "3D NAND",
  "max_memory_size": "500GB",
  "tdp": "Low-power SSD (varies depending on usage)",
  "packaging": "Boxed (M.2 SSD + Documentation)",
  "image": "/static/images/SSD.webp",
  "price": 39.00
},

{
  "id": "ssd-p3plus-1tb",
  "name": "Crucial P3 Plus 1TB",
  "brand": "Crucial",
  "category": "Internal NVMe SSD",
  "application": "Storage",
  "description": "Crucial P3 Plus 1TB is a PCIe Gen4 NVMe SSD designed for fast performance at a budget-friendly price. With speeds up to 5000/4200 MB/s and HMB support in place of DRAM, it offers quick load times, smooth OS performance, and faster data access compared to SATA drives. Ideal for gaming PCs, productivity builds, and laptop upgrades where high-speed storage is needed without premium cost.",
  "series": "p3",
  "socket": "M.2 NVMe (PCIe 4.0 x4)",
  "capacity": "1TB",
  "cache": "HMB Technology (No onboard DRAM)",
  "read_speed": "Up to 5000 MB/s",
  "write_speed": "Up to 4200 MB/s",
  "tech": "Micron 3D NAND",
  "memory_type": "3D NAND",
  "max_memory_size": "1TB",
  "tdp": "Power efficient NVMe (usage-dependent)",
  "packaging": "Boxed (M.2 SSD + Documentation)",
  "image": "/static/images/SSD.webp",
  "price": 69.00
},

{
  "id": "ssd-p5plus-1tb",
  "name": "Crucial P5 Plus 1TB",
  "brand": "Crucial",
  "category": "Internal NVMe SSD",
  "application": "Storage",
  "description": "Crucial P5 Plus 1TB is a high-performance PCIe 4.0 NVMe SSD designed for gaming systems, workstations, and intensive workloads. Built with Micron 176-layer 3D TLC NAND and onboard DRAM cache, it delivers blazing speeds up to 6600/5000 MB/s for fast boot times, quick application loading, 4K/8K editing, and smooth gaming performance. Ideal for high-speed PC builds, PS5 compatibility, and heavy multitasking environments.",
  "series": "p5",
  "socket": "M.2 NVMe (PCIe 4.0 x4)",
  "capacity": "1TB",
  "cache": "1GB LPDDR4 DRAM",
  "read_speed": "Up to 6600 MB/s",
  "write_speed": "Up to 5000 MB/s",
  "tech": "Micron 176-layer 3D TLC NAND",
  "memory_type": "TLC NAND",
  "max_memory_size": "1TB",
  "tdp": "Low/Moderate power depending on workload",
  "packaging": "Boxed (M.2 SSD + Documentation)",
  "image": "/static/images/SSD.webp",
  "price": 89.00
},

{
  "id": "ssd-t700-2tb",
  "name": "Crucial T700 2TB",
  "brand": "Crucial",
  "category": "Internal NVMe SSD",
  "application": "Storage",
  "description": "Crucial T700 2TB is an ultra-high-performance PCIe Gen5 NVMe SSD delivering extreme speeds up to 12,000/11,500 MB/s, designed for next-generation gaming PCs, workstations, 4K/8K editing, AI workloads, and heavy multitasking. Built with Micron 232-layer TLC NAND and onboard DRAM cache, it provides fast load times, superior responsiveness, and massive data throughput. Best used with a heatsink for optimal thermals, especially during sustained transfers.",
  "series": "t700",
  "socket": "M.2 NVMe (PCIe 5.0 x4)",
  "capacity": "2TB",
  "cache": "2GB LPDDR4 DRAM",
  "read_speed": "Up to 12000 MB/s",
  "write_speed": "Up to 11500 MB/s",
  "tech": "Micron 232-layer 3D TLC NAND",
  "memory_type": "TLC NAND",
  "max_memory_size": "2TB",
  "tdp": "Higher-power Gen5 SSD (enhanced cooling recommended)",
  "packaging": "Boxed (M.2 SSD + Documentation) — available with/without heatsink",
  "image": "/static/images/SSD.webp",
  "price": 299.00
},


#  MICRON SSD


{
  "id": "ssd-micron2400-512gb",
  "name": "Micron 2400 512GB",
  "brand": "Micron",
  "category": "Internal NVMe SSD",
  "application": "Storage",
  "description": "Micron 2400 512GB is an NVMe PCIe 4.0 SSD offering solid performance for everyday computing, OS / application installation and moderate data workloads. With read speeds up to ~3500 MB/s and write up to ~3000 MB/s, it is significantly faster than SATA SSDs and suitable for compact laptops or desktops needing a fast boot drive with moderate capacity.",
  "series": "2400",
  "socket": "M.2 NVMe (PCIe 4.0 x4)",
  "capacity": "512GB",
  "cache": "HMB (No onboard DRAM)",
  "read_speed": "Up to 3500 MB/s",
  "write_speed": "Up to 3000 MB/s",
  "tech": "Micron 3D NAND",
  "memory_type": "3D NAND",
  "max_memory_size": "512GB",
  "tdp": "Low-power SSD (varies with load)",
  "packaging": "Boxed (M.2 SSD + Documentation)",
  "image": "/static/images/SSD.webp",
  "price": 55.00
},

{
  "id": "ssd-micron2450-1tb",
  "name": "Micron 2450 1TB",
  "brand": "Micron",
  "category": "Internal NVMe SSD",
  "application": "Storage",
  "description": "Micron 2450 1TB is an entry-to-mid-level PCIe 4.0 NVMe SSD offering solid storage performance at an affordable price. With sequential read speeds up to 3400 MB/s and write speeds up to 3000 MB/s, it is well suited for OS drives, application loading, lightweight gaming, and everyday productivity tasks. Its 1TB capacity provides ample storage for users seeking fast NVMe performance without premium pricing.",
  "series": "2400",
  "socket": "M.2 NVMe (PCIe 4.0 x4)",
  "capacity": "1TB",
  "cache": "HMB (Host Memory Buffer, no onboard DRAM)",
  "read_speed": "Up to 3400 MB/s",
  "write_speed": "Up to 3000 MB/s",
  "tech": "Micron 3D NAND",
  "memory_type": "3D NAND",
  "max_memory_size": "1TB",
  "tdp": "Power efficient SSD (workload dependent)",
  "packaging": "Boxed (M.2 SSD + Documentation)",
  "image": "/static/images/SSD.webp",
  "price": 99.00
},

{
  "id": "ssd-micron3400-1tb",
  "name": "Micron 3400 1TB",
  "price": 139.00,
  "brand": "Micron",
  "category": "Internal NVMe SSD",
  "application": "Storage",
  "description": "Micron 3400 1TB is a high-performance PCIe 4.0 NVMe SSD offering blazing fast read/write speeds (up to 6600/5200 MB/s), onboard DRAM and SLC cache for stable performance, and 1TB capacity — ideal for gaming rigs, content creation workstations, large 4K/8K video editing, and heavy data tasks. It delivers excellent endurance and responsiveness while using modern 3D NAND flash and advanced controller technology.",
  "series": "3400",
  "socket": "M.2 NVMe (PCIe 4.0 x4)",
  "capacity": "1TB",
  "cache": "Onboard DRAM + SLC cache buffer",
  "read_speed": "Up to 6600 MB/s",
  "write_speed": "Up to 5200 MB/s",
  "tech": "Micron 3D TLC NAND (PCIe 4.0)",
  "memory_type": "3D NAND",
  "max_memory_size": "1TB",
  "tdp": "Low-power SSD (variable with workload)",
  "packaging": "Boxed (M.2 SSD + Documentation)",
  "image": "/static/images/SSD.webp",
  "price": 139.00
},

{
  "id": "ssd-micron3500-2tb",
  "name": "Micron 3500 2TB",
  "price": 249.00,
  "brand": "Micron",
  "category": "Internal NVMe SSD",
  "application": "Storage",
  "description": "Micron 3500 2TB is a high-performance PCIe 4.0 NVMe SSD designed for heavy workloads, gaming, content creation and professional use. With very high read/write throughput (up to ~7000/5500 MB/s), onboard DRAM for consistent performance, and a large 2TB capacity, it’s ideal for data-intensive applications, large media libraries, virtualization, and workstation builds. It offers durability, speed and ample storage for modern PC demands.",
  "series": "3400",
  "socket": "M.2 NVMe (PCIe 4.0 x4)",
  "capacity": "2TB",
  "cache": "Onboard DRAM + SLC cache buffer",
  "read_speed": "Up to 7000 MB/s (theoretical / peak)",
  "write_speed": "Up to 5500 MB/s (theoretical / peak)",
  "tech": "Micron 3D TLC NAND (PCIe 4.0)",
  "memory_type": "3D NAND",
  "max_memory_size": "2TB",
  "tdp": "Low-power SSD (power varies with workload)",
  "packaging": "Boxed (M.2 SSD + Documentation)",
  "image": "/static/images/SSD.webp",
  "price": 249.00
},

{
  "id": "ssd-5400-3_8tb",
  "name": "Micron 5400 3.8TB",
  "price": 499.00,
  "brand": "Micron",
  "category": "Enterprise SSD",
  "application": "Server / Data Storage",
  "description": "Micron 5400 3.8TB is a high-capacity enterprise-class NVMe SSD built for datacenter, server, and storage-heavy workloads. With enterprise-grade TTL NAND, DRAM cache and optimized firmware, it delivers reliable sustained performance, high endurance, and low-latency storage for heavy I/O, virtualization, databases, and large storage arrays. Its 3.8TB capacity is ideal for server storage pools, backup solutions, and high throughput applications requiring both capacity and performance.",
  "series": "5400",
  "socket": "U.2 NVMe (PCIe 3.1 x4) / M.2 22110 NVMe",
  "capacity": "3.8TB",
  "cache": "Enterprise-grade DRAM cache + internal controller cache",
  "read_speed": "Up to ~3400 MB/s",
  "write_speed": "Up to ~3000 MB/s",
  "tech": "Micron 3D TLC NAND (Enterprise-grade, optimized for endurance)",
  "memory_type": "3D TLC NAND",
  "max_memory_size": "3.8TB",
  "tdp": "Enterprise SSD power profile (varies with workload)",
  "packaging": "OEM / Enterprise packaging (drive + documentation)",
  "image": "/static/images/SSD.webp",
  "price": 499.00
},

{
  "id": "ssd-micron6500-7.68tb",
  "name": "Micron 6500 7.68TB",
  "price": 1299.00,
  "brand": "Micron",
  "category": "Enterprise NVMe SSD",
  "application": "Storage / Data Center",
  "description": "Micron 6500 7.68TB is a high-capacity, high-endurance enterprise NVMe SSD designed for data centers, virtualization, large-scale storage systems and heavy I/O workloads. With very high capacity and enterprise-grade NAND, onboard DRAM and internal cache mechanisms, it offers reliable performance, durability, and throughput for mission-critical storage applications, database workloads, and large data archives.",
  "series": "5400",
  "socket": "U.2 / E1.S NVMe (PCIe 4.0 x4)",
  "capacity": "7.68TB",
  "cache": "Onboard DRAM + Internal Cache Buffer",
  "read_speed": "Enterprise-grade NVMe throughput (varies by model/config)",
  "write_speed": "Enterprise-grade NVMe throughput (varies by model/config)",
  "tech": "Micron 3D NAND + NVMe Gen4",
  "memory_type": "3D NAND TLC/TLC-based enterprise NAND",
  "max_memory_size": "7.68TB",
  "tdp": "Enterprise SSD (power varies with workload)",
  "packaging": "OEM / Tray (Enterprise-grade packaging)",
  "image": "/static/images/SSD.webp",
  "price": 1299.00
},

{
  "id": "ssd-micron7500pro-15.36tb",
  "name": "Micron 7500 PRO 15.36TB",
  "price": 3499.00,
  "brand": "Micron",
  "category": "Enterprise NVMe SSD",
  "application": "Storage / Data-Center / Server",
  "description": "Micron 7500 PRO 15.36TB is a high-capacity, enterprise-grade NVMe SSD designed for data centres, enterprise storage arrays, heavy I/O workloads, virtualization, large-scale database workloads, and archival systems. With massive 15.36 TB capacity, onboard DRAM, internal cache mechanisms, and PCIe 4.0 NVMe interface, it provides high endurance, stable performance under heavy load, and reliable storage for mission-critical workloads.",
  "series": "7500",
  "socket": "U.2 / E1.S NVMe (PCIe 4.0 x4)",
  "capacity": "15.36TB",
  "cache": "Onboard DRAM + SLC cache buffer",
  "read_speed": "Enterprise-class NVMe throughput (varies with workload)",
  "write_speed": "Enterprise-class NVMe throughput (varies with workload)",
  "tech": "Micron 3D TLC NAND, PCIe 4.0 NVMe",
  "memory_type": "3D TLC NAND",
  "max_memory_size": "15.36TB",
  "tdp": "Enterprise SSD – variable power consumption depending on load",
  "packaging": "OEM / Tray (Enterprise packaging)",
  "image": "/static/images/SSD.webp",
  "price": 3499.00


}
]
